package visual.tela_cliente;

/*import controle.ClienteControl;*/
import controle.Dados;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import modelo.ClientePessoaFisicaBean;
import modelo.ClientePessoaJuridicaBean;
import util.TabelaAbstrataClientes;
import static visual.tela_principal.TelaPrincipalDoSistema.facade;

/**
 * @author Marcelo Henrique
 */
public class PainelPesquisarClientes extends javax.swing.JPanel {

    public PainelPesquisarClientes() {
        initComponents();
        mostrarTabelaDeClientes();
       
    }

    public static void mostrarTabelaDeClientes() {
        facade.listarClientes();
        
        tabelaClientes.setModel(new TabelaAbstrataClientes(Dados.listaDeClientesResumo));
        
        tabelaClientes.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,boolean isSelected, boolean hasFocus, int row, int column) {
      
            Component result = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (isSelected) {
                    // pinta a linha de laranja
                    result.setBackground(new Color(255, 153, 51));
                    setForeground(Color.WHITE);
                }else{
                    result.setBackground(Color.WHITE);
                    setForeground(Color.BLACK);
                }

                return result; 
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        campoPesquisarCliente = new javax.swing.JTextField();
        campoPesquisaCliente2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(469, 419));

        tabelaClientes.setAutoCreateRowSorter(true);
        tabelaClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelaClientes.setFocusable(false);
        tabelaClientes.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaClientes.setPreferredSize(new java.awt.Dimension(1200, 480));
        tabelaClientes.setRequestFocusEnabled(false);
        tabelaClientes.setRowHeight(30);
        tabelaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoPesquisarCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campoPesquisarCliente.setForeground(new java.awt.Color(51, 51, 51));
        campoPesquisarCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoPesquisarCliente.setBorder(null);
        campoPesquisarCliente.setOpaque(false);
        campoPesquisarCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPesquisarClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPesquisarClienteFocusLost(evt);
            }
        });
        campoPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPesquisarClienteKeyReleased(evt);
            }
        });
        jPanel1.add(campoPesquisarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 430, 30));

        campoPesquisaCliente2.setEditable(false);
        campoPesquisaCliente2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoPesquisaCliente2.setForeground(new java.awt.Color(153, 153, 153));
        campoPesquisaCliente2.setText("Digite o nome do cliente");
        campoPesquisaCliente2.setBorder(null);
        jPanel1.add(campoPesquisaCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 430, 30));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_principal_do_sistema/pesquisa_veiculos.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, 53));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void tabelaClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseReleased
        popularPainelEditar();
        PainelEditarClientes.campoSelecionePFouPJEditar.setEnabled(false);
    }//GEN-LAST:event_tabelaClientesMouseReleased

    
    private void personalizandoCampoUsuario(Color cor) {
        if (campoPesquisarCliente.getText().isEmpty()) {
            campoPesquisaCliente2.setVisible(true);
            campoPesquisaCliente2.setBackground(cor);
            campoPesquisarCliente.setOpaque(false);
        }
        if (!campoPesquisarCliente.getText().isEmpty()) {
            campoPesquisarCliente.setOpaque(true);
            campoPesquisarCliente.setBackground(cor);
            campoPesquisaCliente2.setVisible(false);
        }
    }
                     
    
    private void campoPesquisarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarClienteKeyReleased
        personalizandoCampoUsuario(new Color(255, 255, 153));
        facade.pesquisarCliente(campoPesquisarCliente.getText());
    }//GEN-LAST:event_campoPesquisarClienteKeyReleased

    private void campoPesquisarClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesquisarClienteFocusGained
       personalizandoCampoUsuario(new Color(255, 255, 153));
        
    }//GEN-LAST:event_campoPesquisarClienteFocusGained

    private void campoPesquisarClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesquisarClienteFocusLost
        personalizandoCampoUsuario(new Color(255, 255, 255));
        
    }//GEN-LAST:event_campoPesquisarClienteFocusLost

    public void popularPainelEditar() {
        
        if ((tabelaClientes.getSelectedRow() != -1)){
            
            Dados.clientePessoaResumoBean.setCodigo(Integer.parseInt((String.valueOf(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0)))));
            
            String clienteNomeOuNomeFantasia = (String)tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 1);
            String tipoPFOuPJ = (String)(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 2));
            
            if(tipoPFOuPJ.equals("Pessoa Física")){
                facade.listarClientesPessoaFisica();
                
                for(ClientePessoaFisicaBean clientePessoaFisicaBean : Dados.listaDeClientesPessoaFisica){
                    if(clienteNomeOuNomeFantasia.equals(clientePessoaFisicaBean.getNome())){
                        PainelEditarClientes.campoSelecionePFouPJEditar.setSelectedIndex(1);
                        Dados.clienteFisicoEstaticoBean.setCodigo(clientePessoaFisicaBean.getCodigo()); 
                        PainelEditarClientes.campoNomeOuNomeFantasiaEditar.setText(clientePessoaFisicaBean.getNome());
                        PainelEditarClientes.campoEnderecoEditar.setText(clientePessoaFisicaBean.getEndereco());
                        PainelEditarClientes.campoCPFeCNPJEditar.setText(clientePessoaFisicaBean.getCPF());
                    }
                    
                }   
            }
            else if(tipoPFOuPJ.equals("Pessoa Jurídica")){
                facade.listarClientesPessoaJuridica();
                
                for(ClientePessoaJuridicaBean clientePessoaJuridicaBean : Dados.listaDeClientesPessoaJuridica){
                    if(clienteNomeOuNomeFantasia.equals(clientePessoaJuridicaBean.getNomeFantasia())){
                        PainelEditarClientes.campoSelecionePFouPJEditar.setSelectedIndex(2);
                        Dados.clienteJuridicoEstaticoBean.setCodigo(clientePessoaJuridicaBean.getCodigo()); 
                        PainelEditarClientes.campoNomeOuNomeFantasiaEditar.setText(clientePessoaJuridicaBean.getNomeFantasia());
                        PainelEditarClientes.campoEnderecoEditar.setText(clientePessoaJuridicaBean.getEndereco());
                        PainelEditarClientes.campoCPFeCNPJEditar.setText(clientePessoaJuridicaBean.getCNPJ());
                    }
                    
                }  
                
                
            }
            
            
            
            
            

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField campoPesquisaCliente2;
    public static javax.swing.JTextField campoPesquisarCliente;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables
}
