package visual.tela_cliente;

/*import controle.ClienteControl;*/
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import modelo.ClientePessoaFisicaBean;
import modelo.ClientePessoaJuridicaBean;
import modelo.ClientePessoaResumoBean;
import util.TeclasPermitidasApenasLetrasMaiusculas;
import util.TeclasPermitidasParaCpfOuCnpj;
import util.TeclasPermitidasParaEndereco;
import visual.tela_alugar_imovel.PainelAlugarImoveis;
import visual.tela_principal.PainelHome;
import visual.tela_vender_imovel.PainelVenderImoveis;
import visual.tela_principal.TelaPrincipalDoSistema;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoCadastrarCliente;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoDeletarCliente;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoEditarCliente;
import static visual.tela_principal.TelaPrincipalDoSistema.facade;

/**
 * @author Marcelo Henrique
 */
public class PainelCadastrarClientes extends javax.swing.JPanel {


    public PainelCadastrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNomeOuNomeFantasia = new javax.swing.JTextField();
        textoCPFOuCNPJ = new javax.swing.JLabel();
        campoCPFOuCNPJ = new javax.swing.JTextField();
        txtIdade = new javax.swing.JLabel();
        textoEndereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        botaoSalvarCadastroDeCliente = new javax.swing.JButton();
        textoNomeOuNomeFantasia = new javax.swing.JLabel();
        campoSelecionePFouPJ = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(230, 228, 228));
        setMaximumSize(new java.awt.Dimension(860, 520));
        setMinimumSize(new java.awt.Dimension(860, 520));
        setPreferredSize(new java.awt.Dimension(860, 520));

        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setMaximumSize(new java.awt.Dimension(860, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Tipo de Pessoa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        campoNomeOuNomeFantasia.setDocument(new TeclasPermitidasApenasLetrasMaiusculas());
        campoNomeOuNomeFantasia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoNomeOuNomeFantasia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoNomeOuNomeFantasia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNomeOuNomeFantasiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeOuNomeFantasiaFocusLost(evt);
            }
        });
        campoNomeOuNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNomeOuNomeFantasiaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNomeOuNomeFantasiaKeyReleased(evt);
            }
        });
        jPanel1.add(campoNomeOuNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 600, 30));

        textoCPFOuCNPJ.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        textoCPFOuCNPJ.setText("CPF/CNPJ:");
        jPanel1.add(textoCPFOuCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        campoCPFOuCNPJ.setDocument(new TeclasPermitidasParaCpfOuCnpj());
        campoCPFOuCNPJ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoCPFOuCNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoCPFOuCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCPFOuCNPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPFOuCNPJFocusLost(evt);
            }
        });
        campoCPFOuCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCPFOuCNPJActionPerformed(evt);
            }
        });
        jPanel1.add(campoCPFOuCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 270, 30));

        txtIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 80, 86, 30));

        textoEndereco.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        textoEndereco.setText("Endereço:");
        jPanel1.add(textoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, -1));

        campoEndereco.setDocument(new TeclasPermitidasParaEndereco());
        campoEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEnderecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEnderecoFocusLost(evt);
            }
        });
        campoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(campoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 600, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_cliente/botao_cancelar_cadastro_cliente.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(150, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 150, 40));

        botaoSalvarCadastroDeCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoSalvarCadastroDeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_cliente/botao_salvar_cliente.png"))); // NOI18N
        botaoSalvarCadastroDeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSalvarCadastroDeCliente.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoSalvarCadastroDeCliente.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoSalvarCadastroDeCliente.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoSalvarCadastroDeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarCadastroDeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(botaoSalvarCadastroDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 150, 40));

        textoNomeOuNomeFantasia.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        textoNomeOuNomeFantasia.setText("Nome/Nome Fantasia:");
        jPanel1.add(textoNomeOuNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        campoSelecionePFouPJ.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoSelecionePFouPJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione -- Pessoa Física ou Pessoa Jurídica", "Pessoa Física", "Pessoa Jurídica" }));
        campoSelecionePFouPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoSelecionePFouPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSelecionePFouPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSelecionePFouPJFocusLost(evt);
            }
        });
        campoSelecionePFouPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSelecionePFouPJActionPerformed(evt);
            }
        });
        jPanel1.add(campoSelecionePFouPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 600, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        botaoCadastrarCliente.setEnabled(true);
        botaoEditarCliente.setEnabled(true);
        botaoDeletarCliente.setEnabled(true);
        
        TelaPrincipalDoSistema.exibirPainelPesquisarCliente();
        limparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private boolean validarCamposCliente(){
        if((campoSelecionePFouPJ.getSelectedIndex() != 0) && (!campoNomeOuNomeFantasia.getText().isEmpty()) && (!campoEndereco.getText().isEmpty()) && (!campoCPFOuCNPJ.getText().isEmpty())  ){
            return true;
        } else{
            return false;
        }

    }
    
    ClientePessoaResumoBean clientePessoaResumoBean;
    ClientePessoaJuridicaBean clientePessoaJuridicaBean;
    ClientePessoaFisicaBean clientePessoaFisicaBean;
    private void botaoSalvarCadastroDeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarCadastroDeClienteActionPerformed

        if (validarCamposCliente() == true) {
            
            
            if(campoSelecionePFouPJ.getSelectedIndex() == 1){
                clientePessoaFisicaBean = new ClientePessoaFisicaBean();

                clientePessoaFisicaBean.setNome(campoNomeOuNomeFantasia.getText().trim());
                clientePessoaFisicaBean.setEndereco(campoEndereco.getText().trim());
                clientePessoaFisicaBean.setCPF(campoCPFOuCNPJ.getText().trim());
                clientePessoaFisicaBean.setTipo(campoSelecionePFouPJ.getSelectedItem().toString());

                facade.cadastrarClientePessoaFisica(clientePessoaFisicaBean);
                
                PainelDeDialogoCadastrarCliente alertaDeDialogoCadastrarClientePF = new PainelDeDialogoCadastrarCliente(null, true);
                alertaDeDialogoCadastrarClientePF.setLocationRelativeTo(null);
                alertaDeDialogoCadastrarClientePF.setVisible(true);

            }
            else if(campoSelecionePFouPJ.getSelectedIndex() == 2){
                clientePessoaJuridicaBean = new ClientePessoaJuridicaBean();

                clientePessoaJuridicaBean.setNomeFantasia(campoNomeOuNomeFantasia.getText().trim());
                clientePessoaJuridicaBean.setEndereco(campoEndereco.getText().trim());
                clientePessoaJuridicaBean.setCNPJ(campoCPFOuCNPJ.getText().trim());
                clientePessoaJuridicaBean.setTipo(campoSelecionePFouPJ.getSelectedItem().toString());
            
                facade.cadastrarClientePessoaJuridica(clientePessoaJuridicaBean);
                
                PainelDeDialogoCadastrarCliente alertaDeDialogoCadastrarClientePJ = new PainelDeDialogoCadastrarCliente(null, true);
                alertaDeDialogoCadastrarClientePJ.setLocationRelativeTo(null);
                alertaDeDialogoCadastrarClientePJ.setVisible(true);
            }

                clientePessoaResumoBean = new ClientePessoaResumoBean();
                clientePessoaResumoBean.setCliente(campoNomeOuNomeFantasia.getText().trim());
                clientePessoaResumoBean.setTipo(campoSelecionePFouPJ.getSelectedItem().toString());
                facade.cadastrarClienteResumo(clientePessoaResumoBean);

                PainelVenderImoveis.campoSelecioneClienteDaCompra.addItem(clientePessoaResumoBean.getCliente());
                PainelAlugarImoveis.campoSelecioneClienteDoAluguel.addItem(clientePessoaResumoBean.getCliente());
            
                limparCampos();

                botaoCadastrarCliente.setEnabled(true);
                botaoEditarCliente.setEnabled(true);
                botaoDeletarCliente.setEnabled(true);
                
                TelaPrincipalDoSistema.exibirPainelPesquisarCliente();
                PainelPesquisarClientes.mostrarTabelaDeClientes();

            // atualiza a contagem de clientes cadastrados no sistema
            // Dados.listaDeClientesResumo.add(clienteBean);
            PainelHome.atualizarResumoDoSistema();

            
        }else{
           
           PainelDeDialogoCliente alertaDialogoCadastrarCliente = new PainelDeDialogoCliente(null, true);
           PainelDeDialogoCliente.textoNomeDialogoCliente.setText("Campo(s) inválido(s)!");
           alertaDialogoCadastrarCliente.setLocationRelativeTo(null);
           alertaDialogoCadastrarCliente.setVisible(true);
        }    


    }//GEN-LAST:event_botaoSalvarCadastroDeClienteActionPerformed

    private boolean verificarCampos() {

        if (campoNomeOuNomeFantasia.getText().isEmpty()) {
            JOptionPane.showInternalMessageDialog(this, "ERRO DIGITE UM NOME!");
            return false;
        }
        return true;

    }


    private void campoNomeOuNomeFantasiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeOuNomeFantasiaKeyReleased

    }//GEN-LAST:event_campoNomeOuNomeFantasiaKeyReleased

    private void campoNomeOuNomeFantasiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeOuNomeFantasiaKeyPressed

    }//GEN-LAST:event_campoNomeOuNomeFantasiaKeyPressed

    public String auxiliar = "";
    private void campoNomeOuNomeFantasiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeOuNomeFantasiaFocusGained
        campoNomeOuNomeFantasia.setBorder(new LineBorder(new Color(255,153,51),2,true));
    }//GEN-LAST:event_campoNomeOuNomeFantasiaFocusGained

    private void campoNomeOuNomeFantasiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeOuNomeFantasiaFocusLost
        campoNomeOuNomeFantasia.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoNomeOuNomeFantasiaFocusLost

    private void campoCPFOuCNPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFOuCNPJFocusGained
        campoCPFOuCNPJ.setBorder(new LineBorder(new Color(255,153,51),2,true));
       
    }//GEN-LAST:event_campoCPFOuCNPJFocusGained

    private void campoCPFOuCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFOuCNPJFocusLost
        campoCPFOuCNPJ.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoCPFOuCNPJFocusLost

    private void campoEnderecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEnderecoFocusGained
        campoEndereco.setBorder(new LineBorder(new Color(255,153,51),2,true));
      
    }//GEN-LAST:event_campoEnderecoFocusGained

    private void campoEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEnderecoFocusLost
        campoEndereco.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoEnderecoFocusLost

    private void campoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecoActionPerformed

    private void campoCPFOuCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCPFOuCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCPFOuCNPJActionPerformed

    private void campoSelecionePFouPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSelecionePFouPJActionPerformed
       if(campoSelecionePFouPJ.getSelectedIndex() == 0){
           textoNomeOuNomeFantasia.setText("Nome/Nome Fantasia:");
           textoCPFOuCNPJ.setText("CPF/CNPJ:");
       }else if(campoSelecionePFouPJ.getSelectedIndex() == 1){
           textoNomeOuNomeFantasia.setText("Nome:");
           textoCPFOuCNPJ.setText("CPF:");
       }else if(campoSelecionePFouPJ.getSelectedIndex() == 2){
           textoNomeOuNomeFantasia.setText("Nome Fantasia:");
           textoCPFOuCNPJ.setText("CNPJ:");
       }
    }//GEN-LAST:event_campoSelecionePFouPJActionPerformed

    private void campoSelecionePFouPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecionePFouPJFocusGained

        campoSelecionePFouPJ.setBackground(new Color(255,153,51));
        campoSelecionePFouPJ.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_campoSelecionePFouPJFocusGained

    private void campoSelecionePFouPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecionePFouPJFocusLost
       campoSelecionePFouPJ.setBackground(Color.WHITE);
       campoSelecionePFouPJ.setForeground(Color.BLACK);
    }//GEN-LAST:event_campoSelecionePFouPJFocusLost


    private void limparCampos() {
        campoNomeOuNomeFantasia.setText(null);
        campoEndereco.setText(null);
        campoCPFOuCNPJ.setText(null);      
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarCadastroDeCliente;
    private javax.swing.JTextField campoCPFOuCNPJ;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNomeOuNomeFantasia;
    private javax.swing.JComboBox<String> campoSelecionePFouPJ;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoCPFOuCNPJ;
    private javax.swing.JLabel textoEndereco;
    private javax.swing.JLabel textoNomeOuNomeFantasia;
    private javax.swing.JLabel txtIdade;
    // End of variables declaration//GEN-END:variables
}
