package visual.tela_cliente;

/*import controle.ClienteControl;*/
import controle.Dados;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;
import modelo.ClientePessoaFisicaBean;
import modelo.ClientePessoaJuridicaBean;
import modelo.ClientePessoaResumoBean;
import util.TeclasPermitidasParaCpfOuCnpj;
import util.TeclasPermitidasParaEndereco;
import visual.tela_principal.TelaPrincipalDoSistema;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoCadastrarCliente;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoDeletarCliente;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoEditarCliente;
import static visual.tela_principal.TelaPrincipalDoSistema.facade;
import static visual.tela_vender_imovel.PainelEditarVenderImoveis.campoEditarImovelVenderImovel;

/**
 * @author Marcelo Henrique
 */
public class PainelEditarClientes extends javax.swing.JPanel {

    public PainelEditarClientes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoNomeOuNomeFantasiaEditar = new javax.swing.JTextField();
        campoCPFeCNPJEditar = new javax.swing.JTextField();
        campoEnderecoEditar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        botaoEditarClientes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoSelecionePFouPJEditar = new javax.swing.JComboBox<>();
        textoNomeOuNomeFantasiaEditar = new javax.swing.JLabel();
        textoEnderecoEditar = new javax.swing.JLabel();
        textoCPFOuCNPJEditar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 228, 228));
        setMaximumSize(new java.awt.Dimension(860, 520));
        setMinimumSize(new java.awt.Dimension(860, 520));
        setPreferredSize(new java.awt.Dimension(860, 520));

        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setMaximumSize(new java.awt.Dimension(860, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoNomeOuNomeFantasiaEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoNomeOuNomeFantasiaEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoNomeOuNomeFantasiaEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNomeOuNomeFantasiaEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeOuNomeFantasiaEditarFocusLost(evt);
            }
        });
        jPanel1.add(campoNomeOuNomeFantasiaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 600, 30));

        campoCPFeCNPJEditar.setDocument(new TeclasPermitidasParaCpfOuCnpj());
        campoCPFeCNPJEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoCPFeCNPJEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoCPFeCNPJEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCPFeCNPJEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPFeCNPJEditarFocusLost(evt);
            }
        });
        campoCPFeCNPJEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCPFeCNPJEditarActionPerformed(evt);
            }
        });
        jPanel1.add(campoCPFeCNPJEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 260, 30));

        campoEnderecoEditar.setDocument(new TeclasPermitidasParaEndereco());
        campoEnderecoEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoEnderecoEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEnderecoEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEnderecoEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEnderecoEditarFocusLost(evt);
            }
        });
        campoEnderecoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoEditarActionPerformed(evt);
            }
        });
        jPanel1.add(campoEnderecoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 600, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_cliente/botao_cancelar_editar_cliente.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setMaximumSize(new java.awt.Dimension(150, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(150, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 150, 40));

        botaoEditarClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEditarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_cliente/botao_edit_cliente.png"))); // NOI18N
        botaoEditarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEditarClientes.setFocusable(false);
        botaoEditarClientes.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoEditarClientes.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoEditarClientes.setOpaque(false);
        botaoEditarClientes.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoEditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarClientesActionPerformed(evt);
            }
        });
        jPanel1.add(botaoEditarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 150, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de Pessoa:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        campoSelecionePFouPJEditar.setBackground(new java.awt.Color(204, 204, 204));
        campoSelecionePFouPJEditar.setEditable(true);
        campoSelecionePFouPJEditar.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoSelecionePFouPJEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione -- Pessoa Física ou Pessoa Jurídica", "Pessoa Física", "Pessoa Jurídica" }));
        campoSelecionePFouPJEditar.setBorder(null);
        campoSelecionePFouPJEditar.setEnabled(false);
        campoSelecionePFouPJEditar.setRequestFocusEnabled(true);
        campoSelecionePFouPJEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSelecionePFouPJEditarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSelecionePFouPJEditarFocusLost(evt);
            }
        });
        campoSelecionePFouPJEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campoSelecionePFouPJEditarMouseEntered(evt);
            }
        });
        campoSelecionePFouPJEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSelecionePFouPJEditarActionPerformed(evt);
            }
        });
        jPanel1.add(campoSelecionePFouPJEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 600, 30));

        textoNomeOuNomeFantasiaEditar.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        textoNomeOuNomeFantasiaEditar.setText("Nome/Nome Fantasia:");
        jPanel1.add(textoNomeOuNomeFantasiaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, -1));

        textoEnderecoEditar.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        textoEnderecoEditar.setText("Endereço:");
        jPanel1.add(textoEnderecoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, -1));

        textoCPFOuCNPJEditar.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        textoCPFOuCNPJEditar.setText("CPF/CNPJ:");
        jPanel1.add(textoCPFOuCNPJEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        botaoCadastrarCliente.setEnabled(true);
        botaoEditarCliente.setEnabled(true);
        botaoDeletarCliente.setEnabled(true);
        
        TelaPrincipalDoSistema.exibirPainelPesquisarCliente();
        
        limparCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void limparCampos(){
        campoNomeOuNomeFantasiaEditar.setText(null);
        campoEnderecoEditar.setText(null);
        campoCPFeCNPJEditar.setText(null);   
    }
    
    private boolean validarCamposEditarCliente(){
        if((campoSelecionePFouPJEditar.getSelectedIndex() != 0) && (!campoNomeOuNomeFantasiaEditar.getText().isEmpty()) && (!campoEnderecoEditar.getText().isEmpty()) && (!campoCPFeCNPJEditar.getText().isEmpty())  ){
            return true;
        }
        else{
            return false;
        }
 
    }
    
    
    ClientePessoaResumoBean clientePessoaResumoBean;
    private void botaoEditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarClientesActionPerformed

        if(validarCamposEditarCliente() == true){
            
            if(campoSelecionePFouPJEditar.getSelectedIndex() == 1){
                ClientePessoaFisicaBean clientePessoaFisicaBean = new ClientePessoaFisicaBean();
        
                clientePessoaFisicaBean.setCodigo(Dados.clienteFisicoEstaticoBean.getCodigo());
                clientePessoaFisicaBean.setNome(campoNomeOuNomeFantasiaEditar.getText().trim());
                clientePessoaFisicaBean.setEndereco(campoEnderecoEditar.getText().trim());
                clientePessoaFisicaBean.setCPF(campoCPFeCNPJEditar.getText().trim());
                clientePessoaFisicaBean.setTipo(campoSelecionePFouPJEditar.getSelectedItem().toString());
            
                facade.alterarClientePessoaFisica(clientePessoaFisicaBean, clientePessoaFisicaBean.getCodigo());
            
                PainelDeDialogoCadastrarCliente alertaDeDialogoEditarClientePF = new PainelDeDialogoCadastrarCliente(null, true);
                PainelDeDialogoCadastrarCliente.textoNomeDialogoCliente.setText("Cliente Alterado!");
                alertaDeDialogoEditarClientePF.setLocationRelativeTo(null);
                alertaDeDialogoEditarClientePF.setVisible(true);
            }
            else if(campoSelecionePFouPJEditar.getSelectedIndex() == 2){
                ClientePessoaJuridicaBean clientePessoaJuridicaBean = new ClientePessoaJuridicaBean();
        
                clientePessoaJuridicaBean.setCodigo(Dados.clienteJuridicoEstaticoBean.getCodigo());
                clientePessoaJuridicaBean.setNomeFantasia(campoNomeOuNomeFantasiaEditar.getText().trim());
                clientePessoaJuridicaBean.setEndereco(campoEnderecoEditar.getText().trim());
                clientePessoaJuridicaBean.setCNPJ(campoCPFeCNPJEditar.getText().trim());
                clientePessoaJuridicaBean.setTipo(campoSelecionePFouPJEditar.getSelectedItem().toString());
            
                facade.alterarClientePessoaJuridica(clientePessoaJuridicaBean, clientePessoaJuridicaBean.getCodigo());             
            
                PainelDeDialogoCadastrarCliente alertaDeDialogoEditarClientePJ = new PainelDeDialogoCadastrarCliente(null, true);
                PainelDeDialogoCadastrarCliente.textoNomeDialogoCliente.setText("Cliente Alterado!");
                alertaDeDialogoEditarClientePJ.setLocationRelativeTo(null);
                alertaDeDialogoEditarClientePJ.setVisible(true);
            }
            
            //limparCampos();
            
            
            clientePessoaResumoBean = new ClientePessoaResumoBean();
            clientePessoaResumoBean.setCodigo(Dados.clientePessoaResumoBean.getCodigo());
            clientePessoaResumoBean.setCliente(campoNomeOuNomeFantasiaEditar.getText().trim());
            clientePessoaResumoBean.setTipo(campoSelecionePFouPJEditar.getSelectedItem().toString());
            
            facade.alterarClienteResumo(clientePessoaResumoBean, clientePessoaResumoBean.getCodigo() );
            
            botaoCadastrarCliente.setEnabled(true);
            botaoEditarCliente.setEnabled(true);
            botaoDeletarCliente.setEnabled(true);
            
            //PainelVenderImoveis.campoSelecioneClienteDaCompra.removeAllItems();
            //PainelVenderImoveis.campoSelecioneClienteDaCompra.addItem("Selecione um Cliente");
            //PainelVenderImoveis.selecionarClientes();
            
            TelaPrincipalDoSistema.exibirPainelPesquisarCliente();
            PainelPesquisarClientes.mostrarTabelaDeClientes();
            
            
        }
        else{
           PainelDeDialogoCliente alertaDialogoEditarCliente = new PainelDeDialogoCliente(null, true);
           PainelDeDialogoCliente.textoNomeDialogoCliente.setText("Campo(s) inválido(s)!");
           alertaDialogoEditarCliente.setLocationRelativeTo(null);
           alertaDialogoEditarCliente.setVisible(true);
        }
        
        
    }//GEN-LAST:event_botaoEditarClientesActionPerformed

    private void campoNomeOuNomeFantasiaEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeOuNomeFantasiaEditarFocusGained
        campoNomeOuNomeFantasiaEditar.setBorder(new LineBorder(new Color(255,153,51),2,true));
    }//GEN-LAST:event_campoNomeOuNomeFantasiaEditarFocusGained

    private void campoNomeOuNomeFantasiaEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeOuNomeFantasiaEditarFocusLost
        campoNomeOuNomeFantasiaEditar.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoNomeOuNomeFantasiaEditarFocusLost

    private void campoCPFeCNPJEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFeCNPJEditarFocusGained
        campoCPFeCNPJEditar.setBorder(new LineBorder(new Color(255,153,51),2,true));
    }//GEN-LAST:event_campoCPFeCNPJEditarFocusGained

    private void campoCPFeCNPJEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFeCNPJEditarFocusLost
        campoCPFeCNPJEditar.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoCPFeCNPJEditarFocusLost

    private void campoEnderecoEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEnderecoEditarFocusGained
        campoEnderecoEditar.setBorder(new LineBorder(new Color(255,153,51),2,true));
    }//GEN-LAST:event_campoEnderecoEditarFocusGained

    private void campoEnderecoEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEnderecoEditarFocusLost
        campoEnderecoEditar.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoEnderecoEditarFocusLost

    private void campoCPFeCNPJEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCPFeCNPJEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCPFeCNPJEditarActionPerformed

    private void campoEnderecoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecoEditarActionPerformed

    private void campoSelecionePFouPJEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSelecionePFouPJEditarActionPerformed
        if(campoSelecionePFouPJEditar.getSelectedIndex() == 0){
           textoNomeOuNomeFantasiaEditar.setText("Nome/Nome Fantasia:");
           textoCPFOuCNPJEditar.setText("CPF/CNPJ:");
       }else if(campoSelecionePFouPJEditar.getSelectedIndex() == 1){
           textoNomeOuNomeFantasiaEditar.setText("Nome:");
           textoCPFOuCNPJEditar.setText("CPF:");
       }else if(campoSelecionePFouPJEditar.getSelectedIndex() == 2){
           textoNomeOuNomeFantasiaEditar.setText("Nome Fantasia:");
           textoCPFOuCNPJEditar.setText("CNPJ:");
       }
    }//GEN-LAST:event_campoSelecionePFouPJEditarActionPerformed

    private void campoSelecionePFouPJEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecionePFouPJEditarFocusGained
        campoSelecionePFouPJEditar.setBackground(new Color(255,153,51));
        campoSelecionePFouPJEditar.setForeground(Color.WHITE);
    }//GEN-LAST:event_campoSelecionePFouPJEditarFocusGained

    private void campoSelecionePFouPJEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecionePFouPJEditarFocusLost
        campoSelecionePFouPJEditar.setBackground(Color.WHITE);
        campoSelecionePFouPJEditar.setForeground(Color.BLACK);
    }//GEN-LAST:event_campoSelecionePFouPJEditarFocusLost

    private void campoSelecionePFouPJEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoSelecionePFouPJEditarMouseEntered
        URL url = getClass().getResource("/imagens/tela_vender_imovel/teste.png");
        Image customimage = new ImageIcon(url).getImage().getScaledInstance(50, 50, 50);      
        Cursor customCursor = Toolkit.getDefaultToolkit().createCustomCursor(customimage, new Point(0, 0), "customCursor");
        
        campoSelecionePFouPJEditar.setCursor(customCursor);
    }//GEN-LAST:event_campoSelecionePFouPJEditarMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoEditarClientes;
    public static javax.swing.JTextField campoCPFeCNPJEditar;
    public static javax.swing.JTextField campoEnderecoEditar;
    public static javax.swing.JTextField campoNomeOuNomeFantasiaEditar;
    public static javax.swing.JComboBox<String> campoSelecionePFouPJEditar;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel textoCPFOuCNPJEditar;
    public static javax.swing.JLabel textoEnderecoEditar;
    public static javax.swing.JLabel textoNomeOuNomeFantasiaEditar;
    // End of variables declaration//GEN-END:variables
}
