package visual.tela_corretor;

import controle.CorretorControl;
import controle.Dados;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import util.TabelaAbstrataCorretores;
import static visual.tela_principal.TelaPrincipalDoSistema.facade;

/**
 * @author Marcelo Henrique
 */
public class PainelPesquisarCorretores extends javax.swing.JPanel {

    public PainelPesquisarCorretores() {
        initComponents();
        mostrarTabelaDeCorretores();
    }

    public static void mostrarTabelaDeCorretores() {
        facade.listarCorretores();
       
        tabelaCorretores.setModel(new TabelaAbstrataCorretores(Dados.listaDeCorretores));
        
        tabelaCorretores.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,boolean isSelected, boolean hasFocus, int row, int column) {
      
            Component resultado = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                        
                if (isSelected) {
                    setBackground(new Color(51, 153, 255));
                    setForeground(Color.WHITE);
                }else{
                    setBackground(Color.WHITE);
                    setForeground(Color.BLACK);
                }

                return resultado; 
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCorretores = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        campoPesquisarCorretor = new javax.swing.JTextField();
        campoPesquisaCorretor2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(469, 419));

        tabelaCorretores.setAutoCreateRowSorter(true);
        tabelaCorretores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabelaCorretores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaCorretores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelaCorretores.setFocusable(false);
        tabelaCorretores.setGridColor(new java.awt.Color(204, 204, 204));
        tabelaCorretores.setPreferredSize(new java.awt.Dimension(1200, 480));
        tabelaCorretores.setRequestFocusEnabled(false);
        tabelaCorretores.setRowHeight(30);
        tabelaCorretores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaCorretores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCorretoresMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaCorretoresMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCorretores);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoPesquisarCorretor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        campoPesquisarCorretor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoPesquisarCorretor.setBorder(null);
        campoPesquisarCorretor.setOpaque(false);
        campoPesquisarCorretor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPesquisarCorretorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPesquisarCorretorFocusLost(evt);
            }
        });
        campoPesquisarCorretor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPesquisarCorretorKeyReleased(evt);
            }
        });
        jPanel1.add(campoPesquisarCorretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 430, 30));

        campoPesquisaCorretor2.setEditable(false);
        campoPesquisaCorretor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoPesquisaCorretor2.setForeground(new java.awt.Color(153, 153, 153));
        campoPesquisaCorretor2.setText("Digite o nome ou o número de registro do corretor");
        campoPesquisaCorretor2.setBorder(null);
        jPanel1.add(campoPesquisaCorretor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 430, 30));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_principal_do_sistema/pesquisa_veiculos.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, 53));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaCorretoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCorretoresMouseClicked
        
    }//GEN-LAST:event_tabelaCorretoresMouseClicked

    private void tabelaCorretoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCorretoresMouseReleased
        popularPainelEditarCorretor();
        
    }//GEN-LAST:event_tabelaCorretoresMouseReleased

    
    private void personalizandoCampoUsuario(Color cor) {
        if (campoPesquisarCorretor.getText().isEmpty()) {
            campoPesquisaCorretor2.setVisible(true);
            campoPesquisaCorretor2.setBackground(cor);
            campoPesquisarCorretor.setOpaque(false);
        }
        if (!campoPesquisarCorretor.getText().isEmpty()) {
            campoPesquisarCorretor.setOpaque(true);
            campoPesquisarCorretor.setBackground(cor);
            campoPesquisaCorretor2.setVisible(false);
        }
    }
                     
    
    private void campoPesquisarCorretorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPesquisarCorretorKeyReleased
        personalizandoCampoUsuario(new Color(255, 255, 153));
        facade.pesquisarCorretor(campoPesquisarCorretor.getText());
    }//GEN-LAST:event_campoPesquisarCorretorKeyReleased

    private void campoPesquisarCorretorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesquisarCorretorFocusGained
        personalizandoCampoUsuario(new Color(255, 255, 153));
        
    }//GEN-LAST:event_campoPesquisarCorretorFocusGained

    private void campoPesquisarCorretorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesquisarCorretorFocusLost
        personalizandoCampoUsuario(new Color(255, 255, 255));
        
    }//GEN-LAST:event_campoPesquisarCorretorFocusLost

    public void popularPainelEditarCorretor() {
        if (tabelaCorretores.getSelectedRow() != -1) {
            
            Dados.corretorEstaticoBean.setRegistro(Integer.parseInt(String.valueOf(tabelaCorretores.getValueAt(tabelaCorretores.getSelectedRow(), 0))));
            
            PainelEditarCorretores.campoNomeEditarCorretor.setText((String)tabelaCorretores.getValueAt(tabelaCorretores.getSelectedRow(), 1));
            PainelEditarCorretores.campoImobiliariaVinculadaEditar.setText("IMOBILIÁRIA UEPB");
            
            Dados.corretorSelecaoVenderImoveis = tabelaCorretores.getValueAt(tabelaCorretores.getSelectedRow(), 1).toString();
            
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField campoPesquisaCorretor2;
    public static javax.swing.JTextField campoPesquisarCorretor;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabelaCorretores;
    // End of variables declaration//GEN-END:variables
}
