package visual.tela_imovel;

import controle.Dados;
/*import controle.ImovelControl;*/
import java.awt.Color;
import javax.swing.border.LineBorder;
import modelo.ImovelBean;
import util.TeclasPermitidasApenasLetrasMaiusculas;
import util.TeclasPermitidasParaValorCobrado;
import visual.tela_alugar_imovel.PainelAlugarImoveis;
import visual.tela_vender_imovel.PainelVenderImoveis;
import visual.tela_principal.TelaPrincipalDoSistema;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoCadastrarImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoEditarImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoExcluirImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.facade;
import visual.tela_vender_imovel.PainelEditarVenderImoveis;

/**
 * @author MH
 */
public class PainelCadastrarImoveis extends javax.swing.JPanel {

    public PainelCadastrarImoveis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoSelecioneFinalidadeDoImovel = new javax.swing.JComboBox<>();
        campoValorCobradoDoImovel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoSelecioneTipoDoImovel = new javax.swing.JComboBox<>();
        botaoCadastrarImoveis = new javax.swing.JButton();
        botaoCancelarCadastroDoImovel = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        campoProprietarioDoImovel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 228, 228));
        setMaximumSize(new java.awt.Dimension(860, 520));
        setMinimumSize(new java.awt.Dimension(860, 520));
        setPreferredSize(new java.awt.Dimension(860, 520));

        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setMaximumSize(new java.awt.Dimension(860, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Tipo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        campoSelecioneFinalidadeDoImovel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoSelecioneFinalidadeDoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Alugar", "Vender" }));
        campoSelecioneFinalidadeDoImovel.setBorder(null);
        campoSelecioneFinalidadeDoImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSelecioneFinalidadeDoImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSelecioneFinalidadeDoImovelFocusLost(evt);
            }
        });
        jPanel1.add(campoSelecioneFinalidadeDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 200, 30));

        campoValorCobradoDoImovel.setDocument(new TeclasPermitidasParaValorCobrado());
        campoValorCobradoDoImovel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoValorCobradoDoImovel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoValorCobradoDoImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoValorCobradoDoImovel.setMargin(new java.awt.Insets(4, 4, 4, 4));
        campoValorCobradoDoImovel.setSelectionStart(4);
        campoValorCobradoDoImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoValorCobradoDoImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoValorCobradoDoImovelFocusLost(evt);
            }
        });
        jPanel1.add(campoValorCobradoDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 150, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Finalidade:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        campoSelecioneTipoDoImovel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoSelecioneTipoDoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casa", "Apartamento" }));
        campoSelecioneTipoDoImovel.setBorder(null);
        campoSelecioneTipoDoImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSelecioneTipoDoImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSelecioneTipoDoImovelFocusLost(evt);
            }
        });
        jPanel1.add(campoSelecioneTipoDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 30));

        botaoCadastrarImoveis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCadastrarImoveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_imovel/botao_salvar_imovel.png"))); // NOI18N
        botaoCadastrarImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrarImoveis.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoCadastrarImoveis.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoCadastrarImoveis.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoCadastrarImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarImoveisActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCadastrarImoveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 150, 40));

        botaoCancelarCadastroDoImovel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCancelarCadastroDoImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_imovel/botao_cancelar_cadastro_imovel.png"))); // NOI18N
        botaoCancelarCadastroDoImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelarCadastroDoImovel.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoCancelarCadastroDoImovel.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoCancelarCadastroDoImovel.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoCancelarCadastroDoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarCadastroDoImovelActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCancelarCadastroDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 150, 40));

        jLabel19.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel19.setText("Proprietário:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 30));

        campoProprietarioDoImovel.setDocument(new TeclasPermitidasApenasLetrasMaiusculas());
        campoProprietarioDoImovel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoProprietarioDoImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoProprietarioDoImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoProprietarioDoImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoProprietarioDoImovelFocusLost(evt);
            }
        });
        jPanel1.add(campoProprietarioDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 650, 30));

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Valor Cobrado:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("R$");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 50, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_imovel/helps.png"))); // NOI18N
        jLabel1.setToolTipText("Exemplo: 1000, use 1.000,00");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void botaoCancelarCadastroDoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarCadastroDoImovelActionPerformed
        botaoCadastrarImovel.setEnabled(true);
        botaoEditarImovel.setEnabled(true);
        botaoExcluirImovel.setEnabled(true);
        
        TelaPrincipalDoSistema.exibirPainelPesquisarImovel();
        
        limparCamposImovel();
    }//GEN-LAST:event_botaoCancelarCadastroDoImovelActionPerformed

    private void limparCamposImovel() {
        campoProprietarioDoImovel.setText(null);
        campoSelecioneTipoDoImovel.setSelectedIndex(0);
        campoSelecioneFinalidadeDoImovel.setSelectedIndex(0);
        campoValorCobradoDoImovel.setText(null);  
    }
    
    private boolean validarCamposImovel(){
        if( (!campoProprietarioDoImovel.getText().isEmpty()) && (campoSelecioneTipoDoImovel.getSelectedIndex() != 0) && (campoSelecioneFinalidadeDoImovel.getSelectedIndex() != 0 ) && (!campoValorCobradoDoImovel.getText().isEmpty()) ){
            return true;
        }else{
           return false; 
        }
        
    }
    
    ImovelBean imovelBean;
    private void botaoCadastrarImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarImoveisActionPerformed

        if(validarCamposImovel() == true){

            imovelBean = new ImovelBean();

            imovelBean.setProprietario(campoProprietarioDoImovel.getText().trim());
            imovelBean.setTipo(String.valueOf(campoSelecioneTipoDoImovel.getSelectedItem().toString().trim()));
            imovelBean.setFinalidade(String.valueOf(campoSelecioneFinalidadeDoImovel.getSelectedItem().toString().trim()));
            imovelBean.setValorCobrado("R$ "+ campoValorCobradoDoImovel.getText().trim());
            imovelBean.setStatus("Disponível");

            facade.cadastrarImovel(imovelBean);
            
            PainelDeDialogoCadastrarImovel dialogoCadastrarImovel = new PainelDeDialogoCadastrarImovel(null, true);
            PainelDeDialogoCadastrarImovel.textoCadastroDialogoImovel.setText("Cadastro realizado!");
            dialogoCadastrarImovel.setLocationRelativeTo(null);
            dialogoCadastrarImovel.setVisible(true);
            
            botaoCadastrarImovel.setEnabled(true);
            botaoEditarImovel.setEnabled(true);
            botaoExcluirImovel.setEnabled(true);
            
            facade.listarImoveis();
        
            if(imovelBean.getFinalidade().equals("Vender")){
                PainelVenderImoveis.campoSelecioneImovelDaVenda.addItem(Dados.listaDeImoveis.get(Dados.listaDeImoveis.size()-1).getCodigo().toString());             
            }
            else if(imovelBean.getFinalidade().equals("Alugar")){
                PainelAlugarImoveis.campoSelecioneImovelDoAluguel.addItem(Dados.listaDeImoveis.get(Dados.listaDeImoveis.size()-1).getCodigo().toString());
            }

            limparCamposImovel();
        
        //Dados.listaDeVeiculosResumo.add(veiculoBean);
        //PainelHome.atualizarResumoDoSistema();
  
            TelaPrincipalDoSistema.exibirPainelPesquisarImovel();
            PainelPesquisarImoveis.mostrarTabelaDeImoveis();
        }else{
           PainelDeDialogoImovel dialogoImovel = new PainelDeDialogoImovel(null, true);
           PainelDeDialogoImovel.textoNomeDialogoImovel.setText("Campo(s) inválido(s)!");
           dialogoImovel.setLocationRelativeTo(null);
           dialogoImovel.setVisible(true);
        }
        
    }//GEN-LAST:event_botaoCadastrarImoveisActionPerformed

    private void campoSelecioneTipoDoImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneTipoDoImovelFocusGained
        campoSelecioneTipoDoImovel.setBackground(new Color(255,204,0));
        campoSelecioneTipoDoImovel.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_campoSelecioneTipoDoImovelFocusGained

    private void campoSelecioneTipoDoImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneTipoDoImovelFocusLost
        campoSelecioneTipoDoImovel.setBackground(Color.WHITE);
        campoSelecioneTipoDoImovel.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_campoSelecioneTipoDoImovelFocusLost

    private void campoSelecioneFinalidadeDoImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneFinalidadeDoImovelFocusGained
        campoSelecioneFinalidadeDoImovel.setBackground(new Color(255,204,0));
        campoSelecioneFinalidadeDoImovel.setForeground(Color.BLACK);
    }//GEN-LAST:event_campoSelecioneFinalidadeDoImovelFocusGained

    private void campoSelecioneFinalidadeDoImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneFinalidadeDoImovelFocusLost
        campoSelecioneFinalidadeDoImovel.setBackground(Color.WHITE);
        campoSelecioneFinalidadeDoImovel.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_campoSelecioneFinalidadeDoImovelFocusLost

    private void campoValorCobradoDoImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoValorCobradoDoImovelFocusGained
        campoValorCobradoDoImovel.setBorder(new LineBorder(new Color(255,204,0),2,true));
    }//GEN-LAST:event_campoValorCobradoDoImovelFocusGained

    private void campoValorCobradoDoImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoValorCobradoDoImovelFocusLost
        campoValorCobradoDoImovel.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoValorCobradoDoImovelFocusLost

    private void campoProprietarioDoImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoProprietarioDoImovelFocusGained
        campoProprietarioDoImovel.setBorder(new LineBorder(new Color(255,204,0),2,true));
        
    }//GEN-LAST:event_campoProprietarioDoImovelFocusGained

    private void campoProprietarioDoImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoProprietarioDoImovelFocusLost
        campoProprietarioDoImovel.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoProprietarioDoImovelFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarImoveis;
    private javax.swing.JButton botaoCancelarCadastroDoImovel;
    private javax.swing.JTextField campoProprietarioDoImovel;
    private javax.swing.JComboBox<String> campoSelecioneFinalidadeDoImovel;
    private javax.swing.JComboBox<String> campoSelecioneTipoDoImovel;
    private javax.swing.JTextField campoValorCobradoDoImovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
    
}
