package visual.tela_imovel;

import controle.Dados;
/*import controle.ImovelControl;*/
import java.awt.Color;
import javax.swing.border.LineBorder;
import modelo.ImovelBean;
import util.TeclasPermitidasApenasLetrasMaiusculas;
import util.TeclasPermitidasParaValorCobrado;
import visual.tela_alugar_imovel.PainelAlugarImoveis;
import static visual.tela_imovel.PainelPesquisarImoveis.estaIndisponivel;
import visual.tela_principal.TelaPrincipalDoSistema;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoCadastrarImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoEditarImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoExcluirImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.facade;
import visual.tela_vender_imovel.PainelVenderImoveis;

/**
 * @author Marcelo Henrique
 */
public class PainelEditarImoveis extends javax.swing.JPanel {

    public PainelEditarImoveis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoEditarImoveis = new javax.swing.JButton();
        botaoCancelarEdicaoDoImovel = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        campoEditarProprietarioDoImovel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoEditarSelecaoTipoDoImovel = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        campoEditarSelecaoFinalidadeDoImovel = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        campoEditarValorCobradoDoImovel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoEditarSelecaoStatus = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(230, 228, 228));
        setMaximumSize(new java.awt.Dimension(860, 520));
        setMinimumSize(new java.awt.Dimension(860, 520));
        setPreferredSize(new java.awt.Dimension(860, 520));

        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setMaximumSize(new java.awt.Dimension(860, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoEditarImoveis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoEditarImoveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_imovel/botao_edit_imovel.png"))); // NOI18N
        botaoEditarImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEditarImoveis.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoEditarImoveis.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoEditarImoveis.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoEditarImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarImoveisActionPerformed(evt);
            }
        });
        jPanel1.add(botaoEditarImoveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 150, 40));

        botaoCancelarEdicaoDoImovel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCancelarEdicaoDoImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_imovel/botao_cancelar_editar_imovel.png"))); // NOI18N
        botaoCancelarEdicaoDoImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelarEdicaoDoImovel.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoCancelarEdicaoDoImovel.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoCancelarEdicaoDoImovel.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoCancelarEdicaoDoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarEdicaoDoImovelActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCancelarEdicaoDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 150, 40));

        jLabel19.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel19.setText("Proprietário:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 30));

        campoEditarProprietarioDoImovel.setDocument(new TeclasPermitidasApenasLetrasMaiusculas());
        campoEditarProprietarioDoImovel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoEditarProprietarioDoImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarProprietarioDoImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarProprietarioDoImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarProprietarioDoImovelFocusLost(evt);
            }
        });
        jPanel1.add(campoEditarProprietarioDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 650, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Tipo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));

        campoEditarSelecaoTipoDoImovel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoEditarSelecaoTipoDoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Casa", "Apartamento" }));
        campoEditarSelecaoTipoDoImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarSelecaoTipoDoImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarSelecaoTipoDoImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarSelecaoTipoDoImovelFocusLost(evt);
            }
        });
        campoEditarSelecaoTipoDoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEditarSelecaoTipoDoImovelActionPerformed(evt);
            }
        });
        jPanel1.add(campoEditarSelecaoTipoDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Finalidade:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        campoEditarSelecaoFinalidadeDoImovel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoEditarSelecaoFinalidadeDoImovel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Alugar", "Vender" }));
        campoEditarSelecaoFinalidadeDoImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarSelecaoFinalidadeDoImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarSelecaoFinalidadeDoImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarSelecaoFinalidadeDoImovelFocusLost(evt);
            }
        });
        jPanel1.add(campoEditarSelecaoFinalidadeDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 200, 30));

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Valor Cobrado:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, -1));

        campoEditarValorCobradoDoImovel.setDocument(new TeclasPermitidasParaValorCobrado());
        campoEditarValorCobradoDoImovel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoEditarValorCobradoDoImovel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoEditarValorCobradoDoImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarValorCobradoDoImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarValorCobradoDoImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarValorCobradoDoImovelFocusLost(evt);
            }
        });
        jPanel1.add(campoEditarValorCobradoDoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 150, 30));

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Status:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 30));

        campoEditarSelecaoStatus.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoEditarSelecaoStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Disponível", "Indisponível" }));
        campoEditarSelecaoStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarSelecaoStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarSelecaoStatusFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarSelecaoStatusFocusLost(evt);
            }
        });
        jPanel1.add(campoEditarSelecaoStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 200, 30));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("R$");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 50, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_imovel/helps.png"))); // NOI18N
        jLabel1.setToolTipText("Exemplo: 1000, use 1.000,00");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void botaoCancelarEdicaoDoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarEdicaoDoImovelActionPerformed
        botaoCadastrarImovel.setEnabled(true);
        botaoEditarImovel.setEnabled(true);
        botaoExcluirImovel.setEnabled(true);
        
        TelaPrincipalDoSistema.exibirPainelPesquisarImovel();
    }//GEN-LAST:event_botaoCancelarEdicaoDoImovelActionPerformed

    private boolean validarCamposEditarImovel(){
        if( (!campoEditarProprietarioDoImovel.getText().isEmpty()) && (campoEditarSelecaoTipoDoImovel.getSelectedIndex() != 0) && (campoEditarSelecaoFinalidadeDoImovel.getSelectedIndex() != 0 ) && (!campoEditarValorCobradoDoImovel.getText().isEmpty()) && (campoEditarSelecaoStatus.getSelectedIndex() != 0) ){
            return true;
        }else{
           return false; 
        }
        
    }
    
    private void botaoEditarImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarImoveisActionPerformed
       
        if(validarCamposEditarImovel() == true){

            ImovelBean imovelBean = new ImovelBean();

            imovelBean.setCodigo(Dados.imovelEstaticoBean.getCodigo());
            imovelBean.setProprietario(campoEditarProprietarioDoImovel.getText().trim());
            imovelBean.setTipo(campoEditarSelecaoTipoDoImovel.getSelectedItem().toString().trim());
            imovelBean.setFinalidade(campoEditarSelecaoFinalidadeDoImovel.getSelectedItem().toString().trim());
            imovelBean.setValorCobrado("R$ "+ campoEditarValorCobradoDoImovel.getText().trim());
            imovelBean.setStatus(campoEditarSelecaoStatus.getSelectedItem().toString().trim());
            
            
            if(imovelBean.getStatus().equals("Indisponível")){
                if( (imovelBean.getFinalidade().equals("Vender")) && (PainelPesquisarImoveis.estaDisponivel == true) ){
                    PainelVenderImoveis.campoSelecioneImovelDaVenda.removeItem(imovelBean.getCodigo().toString());
                }else if((imovelBean.getFinalidade().equals("Alugar")) && (PainelPesquisarImoveis.estaDisponivel == true)){
                   PainelAlugarImoveis.campoSelecioneImovelDoAluguel.removeItem(imovelBean.getCodigo().toString()); 
                }   
            }

            if(imovelBean.getStatus().equals("Disponível")){
                if( (imovelBean.getFinalidade().equals("Vender")) && (PainelPesquisarImoveis.estaIndisponivel == true) ){
                    PainelVenderImoveis.campoSelecioneImovelDaVenda.addItem(imovelBean.getCodigo().toString());
                }else if((imovelBean.getFinalidade().equals("Alugar")) && (PainelPesquisarImoveis.estaIndisponivel == true)){
                   PainelAlugarImoveis.campoSelecioneImovelDoAluguel.addItem(imovelBean.getCodigo().toString()); 
                }   
            }
            
            
            facade.alterarImovel(imovelBean, imovelBean.getCodigo());

            PainelDeDialogoCadastrarImovel dialogoEditarImovel = new PainelDeDialogoCadastrarImovel(null, true);
            PainelDeDialogoCadastrarImovel.textoCadastroDialogoImovel.setText("Alteração realizada!");
            dialogoEditarImovel.setLocationRelativeTo(null);
            dialogoEditarImovel.setVisible(true);
            
            botaoCadastrarImovel.setEnabled(true);
            botaoEditarImovel.setEnabled(true);
            botaoExcluirImovel.setEnabled(true);
            
            TelaPrincipalDoSistema.exibirPainelPesquisarImovel();
            PainelPesquisarImoveis.mostrarTabelaDeImoveis();
        }else{
           PainelDeDialogoImovel dialogoImovell = new PainelDeDialogoImovel(null, true);
           PainelDeDialogoImovel.textoNomeDialogoImovel.setText("Campo(s) inválido(s)!");
           dialogoImovell.setLocationRelativeTo(null);
           dialogoImovell.setVisible(true);
        
        }
    
        
    }//GEN-LAST:event_botaoEditarImoveisActionPerformed

    private void campoEditarProprietarioDoImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarProprietarioDoImovelFocusGained
        campoEditarProprietarioDoImovel.setBorder(new LineBorder(new Color(255,204,0),2,true));
    }//GEN-LAST:event_campoEditarProprietarioDoImovelFocusGained

    private void campoEditarProprietarioDoImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarProprietarioDoImovelFocusLost
        campoEditarProprietarioDoImovel.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoEditarProprietarioDoImovelFocusLost

    private void campoEditarSelecaoTipoDoImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarSelecaoTipoDoImovelFocusGained
        campoEditarSelecaoTipoDoImovel.setBackground(new Color(255,204,0));
        campoEditarSelecaoTipoDoImovel.setForeground(Color.BLACK);
    }//GEN-LAST:event_campoEditarSelecaoTipoDoImovelFocusGained

    private void campoEditarSelecaoTipoDoImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarSelecaoTipoDoImovelFocusLost
        campoEditarSelecaoTipoDoImovel.setBackground(Color.WHITE);
        campoEditarSelecaoTipoDoImovel.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_campoEditarSelecaoTipoDoImovelFocusLost

    private void campoEditarSelecaoTipoDoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEditarSelecaoTipoDoImovelActionPerformed
        
    }//GEN-LAST:event_campoEditarSelecaoTipoDoImovelActionPerformed

    private void campoEditarSelecaoFinalidadeDoImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarSelecaoFinalidadeDoImovelFocusGained
        campoEditarSelecaoFinalidadeDoImovel.setBackground(new Color(255,204,0));
        campoEditarSelecaoFinalidadeDoImovel.setForeground(Color.BLACK);
    }//GEN-LAST:event_campoEditarSelecaoFinalidadeDoImovelFocusGained

    private void campoEditarSelecaoFinalidadeDoImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarSelecaoFinalidadeDoImovelFocusLost
        campoEditarSelecaoFinalidadeDoImovel.setBackground(Color.WHITE);
        campoEditarSelecaoFinalidadeDoImovel.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_campoEditarSelecaoFinalidadeDoImovelFocusLost

    private void campoEditarValorCobradoDoImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarValorCobradoDoImovelFocusGained
        campoEditarValorCobradoDoImovel.setBorder(new LineBorder(new Color(255,204,0),2,true));
    }//GEN-LAST:event_campoEditarValorCobradoDoImovelFocusGained

    private void campoEditarValorCobradoDoImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarValorCobradoDoImovelFocusLost
        campoEditarValorCobradoDoImovel.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoEditarValorCobradoDoImovelFocusLost

    private void campoEditarSelecaoStatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarSelecaoStatusFocusGained
        campoEditarSelecaoStatus.setBackground(new Color(255,204,0));
        campoEditarSelecaoStatus.setForeground(Color.BLACK);
    }//GEN-LAST:event_campoEditarSelecaoStatusFocusGained

    private void campoEditarSelecaoStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarSelecaoStatusFocusLost
        campoEditarSelecaoStatus.setBackground(Color.WHITE);
        campoEditarSelecaoStatus.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_campoEditarSelecaoStatusFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoCancelarEdicaoDoImovel;
    public static javax.swing.JButton botaoEditarImoveis;
    public static javax.swing.JTextField campoEditarProprietarioDoImovel;
    public static javax.swing.JComboBox<String> campoEditarSelecaoFinalidadeDoImovel;
    public static javax.swing.JComboBox<String> campoEditarSelecaoStatus;
    public static javax.swing.JComboBox<String> campoEditarSelecaoTipoDoImovel;
    public static javax.swing.JTextField campoEditarValorCobradoDoImovel;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
