package visual.tela_principal;

//import controle.UsuarioControl;
import java.awt.Color;
//import modelo.UsuarioBean;

/**
 * @author Marcelo Henrique
 */
public class TelaCadastrarUsuario extends javax.swing.JDialog {

    public TelaCadastrarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoConfirmarUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoConfirmarEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoSobrenome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoConfirmarSenha = new javax.swing.JPasswordField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        botaoCancelar = new javax.swing.JButton();
        botaoCadastrarUsuario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        campoSelecionePerfilDeUsuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar novo usuário");

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sobrenome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 30, 110, 30);

        campoConfirmarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoConfirmarUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoConfirmarUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoConfirmarUsuarioFocusLost(evt);
            }
        });
        jPanel1.add(campoConfirmarUsuario);
        campoConfirmarUsuario.setBounds(560, 90, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirmar Usuário");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 90, 150, 30);

        campoConfirmarEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoConfirmarEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoConfirmarEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoConfirmarEmailFocusLost(evt);
            }
        });
        jPanel1.add(campoConfirmarEmail);
        campoConfirmarEmail.setBounds(170, 270, 580, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 30, 70, 30);

        campoNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeFocusLost(evt);
            }
        });
        jPanel1.add(campoNome);
        campoNome.setBounds(170, 30, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirmar Senha");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 150, 150, 30);

        campoSobrenome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoSobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSobrenomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSobrenomeFocusLost(evt);
            }
        });
        jPanel1.add(campoSobrenome);
        campoSobrenome.setBounds(560, 30, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuário");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 90, 70, 30);

        campoConfirmarSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoConfirmarSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoConfirmarSenhaFocusLost(evt);
            }
        });
        jPanel1.add(campoConfirmarSenha);
        campoConfirmarSenha.setBounds(560, 150, 190, 30);

        campoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSenhaFocusLost(evt);
            }
        });
        jPanel1.add(campoSenha);
        campoSenha.setBounds(170, 150, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Perfil de Usuário");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 330, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Senha");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 150, 70, 30);

        campoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusLost(evt);
            }
        });
        jPanel1.add(campoUsuario);
        campoUsuario.setBounds(170, 90, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-mail");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 210, 70, 30);

        campoEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFocusLost(evt);
            }
        });
        jPanel1.add(campoEmail);
        campoEmail.setBounds(170, 210, 580, 30);

        botaoCancelar.setText("CANCELAR");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCancelar);
        botaoCancelar.setBounds(590, 390, 160, 50);

        botaoCadastrarUsuario.setText("CADASTRAR USUÁRIO");
        botaoCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCadastrarUsuario);
        botaoCadastrarUsuario.setBounds(390, 390, 180, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirmar E-mail");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 270, 140, 30);

        campoSelecionePerfilDeUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoSelecionePerfilDeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Vendedor" }));
        jPanel1.add(campoSelecionePerfilDeUsuario);
        campoSelecionePerfilDeUsuario.setBounds(170, 330, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(801, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed


    //UsuarioBean usuarioBean;
    private void botaoCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarUsuarioActionPerformed
        
        /**
        
        usuarioBean = new UsuarioBean();
        usuarioBean.setNome(campoNome.getText().trim());
        usuarioBean.setSobrenome(campoSobrenome.getText().trim());
        usuarioBean.setUsuario(campoUsuario.getText().trim());
        usuarioBean.setSenha(String.valueOf(campoSenha.getPassword()).trim());
        usuarioBean.setEmail(campoEmail.getText().trim());
        usuarioBean.setPerfilUsuario(campoSelecionePerfilDeUsuario.getSelectedItem().toString().trim());
        
        //UsuarioControl.cadastrarUsuario(usuarioBean);
        dispose();
        
        **/
    }//GEN-LAST:event_botaoCadastrarUsuarioActionPerformed

    private void campoNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusGained
        campoNome.setBackground(Color.YELLOW);
    }//GEN-LAST:event_campoNomeFocusGained

    private void campoNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusLost
        campoNome.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoNomeFocusLost

    private void campoSobrenomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSobrenomeFocusGained
        campoSobrenome.setBackground(Color.YELLOW);
    }//GEN-LAST:event_campoSobrenomeFocusGained

    private void campoSobrenomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSobrenomeFocusLost
        campoSobrenome.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoSobrenomeFocusLost

    private void campoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusGained
        campoUsuario.setBackground(Color.YELLOW);
    }//GEN-LAST:event_campoUsuarioFocusGained

    private void campoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusLost
        campoUsuario.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoUsuarioFocusLost

    private void campoConfirmarUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmarUsuarioFocusGained
        campoConfirmarUsuario.setBackground(Color.YELLOW);
    }//GEN-LAST:event_campoConfirmarUsuarioFocusGained

    private void campoConfirmarUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmarUsuarioFocusLost
       campoConfirmarUsuario.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoConfirmarUsuarioFocusLost

    private void campoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusGained
        campoSenha.setBackground(Color.YELLOW);
    }//GEN-LAST:event_campoSenhaFocusGained

    private void campoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusLost
        campoSenha.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoSenhaFocusLost

    private void campoConfirmarSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmarSenhaFocusGained
        campoConfirmarSenha.setBackground(Color.YELLOW);
    }//GEN-LAST:event_campoConfirmarSenhaFocusGained

    private void campoConfirmarSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmarSenhaFocusLost
        campoConfirmarSenha.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoConfirmarSenhaFocusLost

    private void campoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusGained
        campoEmail.setBackground(Color.YELLOW);
    }//GEN-LAST:event_campoEmailFocusGained

    private void campoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusLost
        campoEmail.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoEmailFocusLost

    private void campoConfirmarEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmarEmailFocusGained
        campoConfirmarEmail.setBackground(Color.YELLOW);
    }//GEN-LAST:event_campoConfirmarEmailFocusGained

    private void campoConfirmarEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmarEmailFocusLost
        campoConfirmarEmail.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoConfirmarEmailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastrarUsuario dialog = new TelaCadastrarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarUsuario;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JTextField campoConfirmarEmail;
    private javax.swing.JPasswordField campoConfirmarSenha;
    private javax.swing.JTextField campoConfirmarUsuario;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JComboBox<String> campoSelecionePerfilDeUsuario;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoSobrenome;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
