package visual.tela_alugar_imovel;

import visual.tela_vender_imovel.*;
/*import controle.ClienteControl;*/
import controle.CorretorControl;
import controle.Dados;
/*import controle.ImovelControl;*/
import controle.VenderImovelControl;
import java.awt.Color;
import java.util.Calendar;
import modelo.ClientePessoaResumoBean;
import modelo.CorretorBean;
import modelo.ImovelBean;
import modelo.VenderImovelBean;
import visual.tela_principal.TelaPrincipalDoSistema;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoBuscarAluguelDeImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoEditarAlugarImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.botaoExcluirAlugarImovel;
import static visual.tela_principal.TelaPrincipalDoSistema.facade;

/**
 * @author Marcelo Henrique
 */
public class PainelEditarAlugarImoveis extends javax.swing.JPanel {

    Calendar c = Calendar.getInstance();

    public PainelEditarAlugarImoveis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoGrupoContrato = new javax.swing.ButtonGroup();
        botaoGrupoPeriodo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoVenderImovel = new javax.swing.JButton();
        botaoCancelarEditarVenderImovel = new javax.swing.JButton();
        campoEditarValorNegociadoDaVenda = new javax.swing.JTextField();
        campoEditarClienteVenderImovel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoEditarCorretorVenderImovel = new javax.swing.JTextField();
        campoEditarImovelVenderImovel = new javax.swing.JTextField();
        txtDataEntega = new javax.swing.JLabel();
        campoDataDaVenda = new javax.swing.JTextField();
        txtDataEntega1 = new javax.swing.JLabel();
        campoDataDaVenda1 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setMaximumSize(new java.awt.Dimension(860, 520));
        setMinimumSize(new java.awt.Dimension(860, 520));
        setPreferredSize(new java.awt.Dimension(860, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Corretor:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Imovel:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Valor Negociado:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 150, 30));

        botaoVenderImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_alugar_imovel/botao_edit_alugar_imovel.png"))); // NOI18N
        botaoVenderImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVenderImovel.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoVenderImovel.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoVenderImovel.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoVenderImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVenderImovelActionPerformed(evt);
            }
        });
        add(botaoVenderImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 150, 40));

        botaoCancelarEditarVenderImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_alugar_imovel/botao_cancelar_editar_alugar_imovel.png"))); // NOI18N
        botaoCancelarEditarVenderImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelarEditarVenderImovel.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoCancelarEditarVenderImovel.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoCancelarEditarVenderImovel.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoCancelarEditarVenderImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarEditarVenderImovelActionPerformed(evt);
            }
        });
        add(botaoCancelarEditarVenderImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 150, 40));

        campoEditarValorNegociadoDaVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoEditarValorNegociadoDaVenda.setForeground(new java.awt.Color(0, 153, 51));
        campoEditarValorNegociadoDaVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoEditarValorNegociadoDaVenda.setText("0.00");
        campoEditarValorNegociadoDaVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarValorNegociadoDaVenda.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        campoEditarValorNegociadoDaVenda.setMinimumSize(new java.awt.Dimension(2, 30));
        campoEditarValorNegociadoDaVenda.setPreferredSize(new java.awt.Dimension(41, 30));
        campoEditarValorNegociadoDaVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarValorNegociadoDaVendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarValorNegociadoDaVendaFocusLost(evt);
            }
        });
        add(campoEditarValorNegociadoDaVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 200, 30));

        campoEditarClienteVenderImovel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoEditarClienteVenderImovel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoEditarClienteVenderImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarClienteVenderImovel.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        campoEditarClienteVenderImovel.setMinimumSize(new java.awt.Dimension(2, 30));
        campoEditarClienteVenderImovel.setPreferredSize(new java.awt.Dimension(2, 30));
        campoEditarClienteVenderImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarClienteVenderImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarClienteVenderImovelFocusLost(evt);
            }
        });
        campoEditarClienteVenderImovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoEditarClienteVenderImovelKeyReleased(evt);
            }
        });
        add(campoEditarClienteVenderImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 660, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Cliente:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, 30));

        campoEditarCorretorVenderImovel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoEditarCorretorVenderImovel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoEditarCorretorVenderImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarCorretorVenderImovel.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        campoEditarCorretorVenderImovel.setMinimumSize(new java.awt.Dimension(2, 30));
        campoEditarCorretorVenderImovel.setPreferredSize(new java.awt.Dimension(2, 30));
        campoEditarCorretorVenderImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarCorretorVenderImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarCorretorVenderImovelFocusLost(evt);
            }
        });
        campoEditarCorretorVenderImovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoEditarCorretorVenderImovelKeyReleased(evt);
            }
        });
        add(campoEditarCorretorVenderImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 660, 30));

        campoEditarImovelVenderImovel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoEditarImovelVenderImovel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoEditarImovelVenderImovel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoEditarImovelVenderImovel.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        campoEditarImovelVenderImovel.setMinimumSize(new java.awt.Dimension(2, 30));
        campoEditarImovelVenderImovel.setPreferredSize(new java.awt.Dimension(2, 30));
        campoEditarImovelVenderImovel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEditarImovelVenderImovelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEditarImovelVenderImovelFocusLost(evt);
            }
        });
        campoEditarImovelVenderImovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoEditarImovelVenderImovelKeyReleased(evt);
            }
        });
        add(campoEditarImovelVenderImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 660, 30));

        txtDataEntega.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        txtDataEntega.setText("Data de Inicio:");
        add(txtDataEntega, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 30));

        campoDataDaVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoDataDaVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoDataDaVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoDataDaVenda.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        campoDataDaVenda.setMinimumSize(new java.awt.Dimension(2, 30));
        campoDataDaVenda.setPreferredSize(new java.awt.Dimension(2, 30));
        campoDataDaVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDataDaVendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataDaVendaFocusLost(evt);
            }
        });
        campoDataDaVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoDataDaVendaKeyReleased(evt);
            }
        });
        add(campoDataDaVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 210, 30));

        txtDataEntega1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        txtDataEntega1.setText("Data do Fim:");
        add(txtDataEntega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        campoDataDaVenda1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoDataDaVenda1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoDataDaVenda1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoDataDaVenda1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        campoDataDaVenda1.setMinimumSize(new java.awt.Dimension(2, 30));
        campoDataDaVenda1.setPreferredSize(new java.awt.Dimension(2, 30));
        campoDataDaVenda1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDataDaVenda1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDataDaVenda1FocusLost(evt);
            }
        });
        campoDataDaVenda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoDataDaVenda1KeyReleased(evt);
            }
        });
        add(campoDataDaVenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 210, 30));
    }// </editor-fold>//GEN-END:initComponents


    public static boolean jaInvocouListaDeCorretores = false;
    private void selecionarCorretor() {
        if (jaInvocouListaDeCorretores == false) {
            facade.listarCorretoresPeloNome();
            for (CorretorBean corretorBean : Dados.listaDeCorretoresVenderImovel) {
               //campoSelecioneCorretorDaVenda.addItem("CORRETOR(A): |" + corretorBean.getNome() + "|    NÚMERO DE REGISTRO: " + corretorBean.getRegistro());      
            }
            jaInvocouListaDeCorretores = true;
        }     
    }
    
    
    public static boolean jaInvocouListaDeImoveis = false;
    private void selecionarImovel() {
        if (jaInvocouListaDeImoveis == false) {
            facade.listarCodigoDosImoveisVender();
            for (ImovelBean imovelBean : Dados.listaDeImoveisVenderImovel) {
               //campoSelecioneImovelDaVenda.addItem("IMOVEL: |" + imovelBean.getCodigo()+ "|    TIPO: " + imovelBean.getTipo());          
            }
            jaInvocouListaDeImoveis = true;
        }    
    }
    
    public static boolean jaInvocouListaDeClientes = false;
    private void selecionarCliente() {
        if (jaInvocouListaDeClientes == false) {
            facade.ordenarClientesPeloNome();
            for (ClientePessoaResumoBean clientePessoaResumoBean : Dados.listaDeClientesResumo) {
               //campoSelecioneClienteDaCompra.addItem("CLIENTE: |" + clientePessoaResumoBean.getCliente()+ "|    TIPO: |" + clientePessoaResumoBean.getTipo()+"| :");          
            }
            jaInvocouListaDeClientes = true;
        }
    }
    
    private void campoEditarValorNegociadoDaVendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarValorNegociadoDaVendaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditarValorNegociadoDaVendaFocusGained

    private void campoEditarValorNegociadoDaVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarValorNegociadoDaVendaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditarValorNegociadoDaVendaFocusLost

   

    VenderImovelBean venderImovelBean;
    private void botaoVenderImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVenderImovelActionPerformed

        venderImovelBean = new VenderImovelBean();
        venderImovelBean.setCodigo(Dados.venderImovelEstaticoBean.getCodigo());
        venderImovelBean.setDataDaVenda(campoEditarClienteVenderImovel.getText());
        venderImovelBean.setCorretor(campoEditarCorretorVenderImovel.getText());
        venderImovelBean.setImovel(campoEditarImovelVenderImovel.getText());
        venderImovelBean.setCliente(campoEditarClienteVenderImovel.getText());
        venderImovelBean.setValorNegociado(campoEditarValorNegociadoDaVenda.getText().trim());
        
        facade.alterarVendaDeImovel(venderImovelBean, venderImovelBean.getCodigo());
        
        TelaPrincipalDoSistema.exibirPainelPesquisarVenderImovel();
        PainelPesquisarVenderImovel.mostrarTabelaVenderImovel();
        
       
    }//GEN-LAST:event_botaoVenderImovelActionPerformed

    Double numero;

    Calendar calendarioPadrao = Calendar.getInstance();
    private void botaoCancelarEditarVenderImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarEditarVenderImovelActionPerformed
        botaoBuscarAluguelDeImovel.setEnabled(false);
        botaoEditarAlugarImovel.setEnabled(true);
        botaoExcluirAlugarImovel.setEnabled(true);
        
        TelaPrincipalDoSistema.exibirPainelPesquisarVenderImovel();
    }//GEN-LAST:event_botaoCancelarEditarVenderImovelActionPerformed

    String pegandoOCodigo = "Selecione |1| imovel disponivel para venda";
    private void campoEditarClienteVenderImovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEditarClienteVenderImovelKeyReleased

    }//GEN-LAST:event_campoEditarClienteVenderImovelKeyReleased

    private void campoEditarClienteVenderImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarClienteVenderImovelFocusLost
        campoEditarClienteVenderImovel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoEditarClienteVenderImovelFocusLost

    private void campoEditarClienteVenderImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarClienteVenderImovelFocusGained
        campoEditarClienteVenderImovel.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_campoEditarClienteVenderImovelFocusGained

   
    String pegaTipoDeCliente;
    
    int contadorJuridico = 1;
    int contadorFisico = 2;
    Double valorFinalSemDesconto;
    private void campoEditarCorretorVenderImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarCorretorVenderImovelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditarCorretorVenderImovelFocusGained

    private void campoEditarCorretorVenderImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarCorretorVenderImovelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditarCorretorVenderImovelFocusLost

    private void campoEditarCorretorVenderImovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEditarCorretorVenderImovelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditarCorretorVenderImovelKeyReleased

    private void campoEditarImovelVenderImovelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarImovelVenderImovelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditarImovelVenderImovelFocusGained

    private void campoEditarImovelVenderImovelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEditarImovelVenderImovelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditarImovelVenderImovelFocusLost

    private void campoEditarImovelVenderImovelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEditarImovelVenderImovelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditarImovelVenderImovelKeyReleased

    private void campoDataDaVendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataDaVendaFocusGained
        campoDataDaVenda.setBackground(new Color(255, 255, 153));
    }//GEN-LAST:event_campoDataDaVendaFocusGained

    private void campoDataDaVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataDaVendaFocusLost
        campoDataDaVenda.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_campoDataDaVendaFocusLost

    private void campoDataDaVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDataDaVendaKeyReleased

    }//GEN-LAST:event_campoDataDaVendaKeyReleased

    private void campoDataDaVenda1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataDaVenda1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataDaVenda1FocusGained

    private void campoDataDaVenda1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDataDaVenda1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataDaVenda1FocusLost

    private void campoDataDaVenda1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDataDaVenda1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataDaVenda1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoCancelarEditarVenderImovel;
    public static javax.swing.ButtonGroup botaoGrupoContrato;
    public static javax.swing.ButtonGroup botaoGrupoPeriodo;
    public static javax.swing.JButton botaoVenderImovel;
    public static javax.swing.JTextField campoDataDaVenda;
    public static javax.swing.JTextField campoDataDaVenda1;
    public static javax.swing.JTextField campoEditarClienteVenderImovel;
    public static javax.swing.JTextField campoEditarCorretorVenderImovel;
    public static javax.swing.JTextField campoEditarImovelVenderImovel;
    public static javax.swing.JTextField campoEditarValorNegociadoDaVenda;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JLabel txtDataEntega;
    public static javax.swing.JLabel txtDataEntega1;
    // End of variables declaration//GEN-END:variables

    private void limparCamposVenderImovel() {
        campoEditarClienteVenderImovel.setText(null);
        //campoSelecioneCorretorDaVenda.setSelectedIndex(0);
        //campoSelecioneImovelDaVenda.setSelectedIndex(0);
        //campoSelecioneClienteDaCompra.setSelectedIndex(0);
        campoEditarValorNegociadoDaVenda.setText("0.00");  
        campoEditarClienteVenderImovel.requestFocus();
    }


}
