package visual.tela_alugar_imovel;

/*import controle.AlugarImovelControl;*/
/*import controle.ClienteControl;*/
import controle.CorretorControl;
import controle.Dados;
import controle.Facade;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.border.LineBorder;
import modelo.AlugarImovelBean;
import modelo.ClientePessoaResumoBean;
import modelo.CorretorBean;
import modelo.ImovelBean;
import util.Command;
import util.TeclasPermitidasParaData;
import visual.tela_principal.TelaPrincipalDoSistema;
import static visual.tela_principal.TelaPrincipalDoSistema.facade;

/**
 * @author Marcelo Henrique
 */
public class PainelAlugarImoveis extends javax.swing.JPanel implements Command{
    
    Calendar c = Calendar.getInstance();

    public PainelAlugarImoveis() {
        initComponents();
        selecionarCorretoresAlugar();
        selecionarImoveisDisponiveisParaAlugar();
        selecionarClientesAlugar();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoGrupoContrato = new javax.swing.ButtonGroup();
        botaoGrupoPeriodo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        campoSelecioneImovelDoAluguel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoVenderImovel = new javax.swing.JButton();
        botaoLimparCamposDaVenda = new javax.swing.JButton();
        campoSelecioneCorretorDoAluguel = new javax.swing.JComboBox<>();
        campoValorNegociadoDoAluguel = new javax.swing.JTextField();
        txtDataEntega = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoSelecioneClienteDoAluguel = new javax.swing.JComboBox<>();
        txtDataEntega1 = new javax.swing.JLabel();
        campoDiaDataDeInicio = new javax.swing.JTextField();
        txtDataEntega2 = new javax.swing.JLabel();
        campoMesDataDeInicio = new javax.swing.JTextField();
        txtDataEntega3 = new javax.swing.JLabel();
        campoAnoDataDeInicio = new javax.swing.JTextField();
        campoDiaDataDoFim = new javax.swing.JTextField();
        txtDataEntega4 = new javax.swing.JLabel();
        campoMesDataDoFim = new javax.swing.JTextField();
        txtDataEntega5 = new javax.swing.JLabel();
        campoAnoDataDoFim = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setMaximumSize(new java.awt.Dimension(860, 520));
        setMinimumSize(new java.awt.Dimension(860, 520));
        setPreferredSize(new java.awt.Dimension(860, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoSelecioneImovelDoAluguel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoSelecioneImovelDoAluguel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o código do imovel disponível para venda" }));
        campoSelecioneImovelDoAluguel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoSelecioneImovelDoAluguel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSelecioneImovelDoAluguelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSelecioneImovelDoAluguelFocusLost(evt);
            }
        });
        campoSelecioneImovelDoAluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campoSelecioneImovelDoAluguelMouseEntered(evt);
            }
        });
        campoSelecioneImovelDoAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSelecioneImovelDoAluguelActionPerformed(evt);
            }
        });
        add(campoSelecioneImovelDoAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 660, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Corretor:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Imovel:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Valor Negociado:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 150, 30));

        botaoVenderImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_alugar_imovel/botao_alugar_imovel.png"))); // NOI18N
        botaoVenderImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoVenderImovel.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoVenderImovel.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoVenderImovel.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoVenderImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVenderImovelActionPerformed(evt);
            }
        });
        add(botaoVenderImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 150, 40));

        botaoLimparCamposDaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela_alugar_imovel/botao_limpar_alugar_imovel.png"))); // NOI18N
        botaoLimparCamposDaVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoLimparCamposDaVenda.setMaximumSize(new java.awt.Dimension(150, 40));
        botaoLimparCamposDaVenda.setMinimumSize(new java.awt.Dimension(150, 40));
        botaoLimparCamposDaVenda.setPreferredSize(new java.awt.Dimension(150, 40));
        botaoLimparCamposDaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparCamposDaVendaActionPerformed(evt);
            }
        });
        add(botaoLimparCamposDaVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 150, 40));

        campoSelecioneCorretorDoAluguel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoSelecioneCorretorDoAluguel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um corretor" }));
        campoSelecioneCorretorDoAluguel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoSelecioneCorretorDoAluguel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSelecioneCorretorDoAluguelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSelecioneCorretorDoAluguelFocusLost(evt);
            }
        });
        campoSelecioneCorretorDoAluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campoSelecioneCorretorDoAluguelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                campoSelecioneCorretorDoAluguelMouseExited(evt);
            }
        });
        campoSelecioneCorretorDoAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSelecioneCorretorDoAluguelActionPerformed(evt);
            }
        });
        add(campoSelecioneCorretorDoAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 660, 30));

        campoValorNegociadoDoAluguel.setEditable(false);
        campoValorNegociadoDoAluguel.setBackground(new java.awt.Color(204, 255, 204));
        campoValorNegociadoDoAluguel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        campoValorNegociadoDoAluguel.setForeground(new java.awt.Color(0, 153, 51));
        campoValorNegociadoDoAluguel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoValorNegociadoDoAluguel.setText("R$ 0,00");
        campoValorNegociadoDoAluguel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoValorNegociadoDoAluguel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoValorNegociadoDoAluguelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoValorNegociadoDoAluguelFocusLost(evt);
            }
        });
        add(campoValorNegociadoDoAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 200, 30));

        txtDataEntega.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        txtDataEntega.setText("Data de Inicio:");
        add(txtDataEntega, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Cliente:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 70, 30));

        campoSelecioneClienteDoAluguel.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        campoSelecioneClienteDoAluguel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um cliente" }));
        campoSelecioneClienteDoAluguel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoSelecioneClienteDoAluguel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSelecioneClienteDoAluguelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSelecioneClienteDoAluguelFocusLost(evt);
            }
        });
        campoSelecioneClienteDoAluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                campoSelecioneClienteDoAluguelMouseEntered(evt);
            }
        });
        campoSelecioneClienteDoAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSelecioneClienteDoAluguelActionPerformed(evt);
            }
        });
        add(campoSelecioneClienteDoAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 660, 30));

        txtDataEntega1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        txtDataEntega1.setText("Data do Fim:");
        add(txtDataEntega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        campoDiaDataDeInicio.setDocument(new TeclasPermitidasParaData());
        campoDiaDataDeInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoDiaDataDeInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoDiaDataDeInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoDiaDataDeInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDiaDataDeInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDiaDataDeInicioFocusLost(evt);
            }
        });
        campoDiaDataDeInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoDiaDataDeInicioKeyReleased(evt);
            }
        });
        add(campoDiaDataDeInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 40, 30));

        txtDataEntega2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDataEntega2.setForeground(new java.awt.Color(204, 204, 204));
        txtDataEntega2.setText("/");
        add(txtDataEntega2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, 30));

        campoMesDataDeInicio.setDocument(new TeclasPermitidasParaData());
        campoMesDataDeInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoMesDataDeInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoMesDataDeInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoMesDataDeInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoMesDataDeInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoMesDataDeInicioFocusLost(evt);
            }
        });
        campoMesDataDeInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoMesDataDeInicioKeyReleased(evt);
            }
        });
        add(campoMesDataDeInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 40, 30));

        txtDataEntega3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDataEntega3.setForeground(new java.awt.Color(204, 204, 204));
        txtDataEntega3.setText("/");
        add(txtDataEntega3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 30));

        campoAnoDataDeInicio.setDocument(new TeclasPermitidasParaData());
        campoAnoDataDeInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoAnoDataDeInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoAnoDataDeInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoAnoDataDeInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoAnoDataDeInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoAnoDataDeInicioFocusLost(evt);
            }
        });
        campoAnoDataDeInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoDataDeInicioActionPerformed(evt);
            }
        });
        campoAnoDataDeInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoAnoDataDeInicioKeyReleased(evt);
            }
        });
        add(campoAnoDataDeInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 70, 30));

        campoDiaDataDoFim.setDocument(new TeclasPermitidasParaData());
        campoDiaDataDoFim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoDiaDataDoFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoDiaDataDoFim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoDiaDataDoFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDiaDataDoFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDiaDataDoFimFocusLost(evt);
            }
        });
        campoDiaDataDoFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoDiaDataDoFimKeyReleased(evt);
            }
        });
        add(campoDiaDataDoFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 40, 30));

        txtDataEntega4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDataEntega4.setForeground(new java.awt.Color(204, 204, 204));
        txtDataEntega4.setText("/");
        add(txtDataEntega4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 30));

        campoMesDataDoFim.setDocument(new TeclasPermitidasParaData());
        campoMesDataDoFim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoMesDataDoFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoMesDataDoFim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoMesDataDoFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoMesDataDoFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoMesDataDoFimFocusLost(evt);
            }
        });
        campoMesDataDoFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoMesDataDoFimKeyReleased(evt);
            }
        });
        add(campoMesDataDoFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 40, 30));

        txtDataEntega5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDataEntega5.setForeground(new java.awt.Color(204, 204, 204));
        txtDataEntega5.setText("/");
        add(txtDataEntega5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 30));

        campoAnoDataDoFim.setDocument(new TeclasPermitidasParaData());
        campoAnoDataDoFim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoAnoDataDoFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoAnoDataDoFim.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        campoAnoDataDoFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoAnoDataDoFimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoAnoDataDoFimFocusLost(evt);
            }
        });
        campoAnoDataDoFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoDataDoFimActionPerformed(evt);
            }
        });
        campoAnoDataDoFim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoAnoDataDoFimKeyReleased(evt);
            }
        });
        add(campoAnoDataDoFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    public static void selecionarCorretoresAlugar() {
        facade.listarCorretoresPeloNomeAlugar();
        for (CorretorBean corretorBean : Dados.listaDeCorretoresAlugarImovel) {
            campoSelecioneCorretorDoAluguel.addItem(corretorBean.getNome());  
        }
                
    }

    public static void selecionarImoveisDisponiveisParaAlugar() {
        facade.listarCodigoDosImoveisAlugar();
        for (ImovelBean imovelBean : Dados.listaDeImoveisAlugarImovel) {
            campoSelecioneImovelDoAluguel.addItem(String.valueOf(imovelBean.getCodigo()));          
        }
            
    }
    
    public static void selecionarClientesAlugar() {
        facade.ordenarClientesPeloNomeAlugar();
        for (ClientePessoaResumoBean clientePessoaResumoBean : Dados.listaDeClientesResumoAlugar) {
            campoSelecioneClienteDoAluguel.addItem(clientePessoaResumoBean.getCliente());          
        }
            
    }
    
    private void campoSelecioneCorretorDoAluguelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneCorretorDoAluguelFocusGained
        campoSelecioneCorretorDoAluguel.setBackground(new Color(255,153,153));
       
    }//GEN-LAST:event_campoSelecioneCorretorDoAluguelFocusGained

    private void campoSelecioneCorretorDoAluguelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneCorretorDoAluguelFocusLost
        campoSelecioneCorretorDoAluguel.setBackground(new Color(255, 255, 255));
        
    }//GEN-LAST:event_campoSelecioneCorretorDoAluguelFocusLost

    private void campoValorNegociadoDoAluguelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoValorNegociadoDoAluguelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorNegociadoDoAluguelFocusGained

    private void campoValorNegociadoDoAluguelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoValorNegociadoDoAluguelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorNegociadoDoAluguelFocusLost

    private boolean validarCamposAlugarImovel() {
        if( (!campoDiaDataDeInicio.getText().isEmpty()) && (!campoMesDataDeInicio.getText().isEmpty()) && (!campoAnoDataDeInicio.getText().isEmpty()) && (!campoDiaDataDoFim.getText().isEmpty()) && (!campoMesDataDoFim.getText().isEmpty()) && (!campoAnoDataDoFim.getText().isEmpty())
            && (campoSelecioneCorretorDoAluguel.getSelectedIndex() != 0) && (campoSelecioneImovelDoAluguel.getSelectedIndex() != 0 ) && (campoSelecioneClienteDoAluguel.getSelectedIndex() != 0) && (!campoValorNegociadoDoAluguel.getText().isEmpty()) ){
            return true;
        }else{
           return false; 
        }
    }
    
    
    AlugarImovelBean alugarImovelBean;
    private void botaoVenderImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVenderImovelActionPerformed

        if(validarCamposAlugarImovel() == true){

            execute();
            
            /*
            String dataDeInicioDoAluguel = campoDiaDataDeInicio.getText() + "/" + campoMesDataDeInicio.getText() + "/" + campoAnoDataDeInicio.getText();
            String dataDoFimDoAluguel = campoDiaDataDoFim.getText() + "/" + campoMesDataDoFim.getText() + "/" + campoAnoDataDoFim.getText();

            alugarImovelBean = new AlugarImovelBean();
            alugarImovelBean.setDataDeInicioDoContrato(dataDeInicioDoAluguel);
            alugarImovelBean.setDataDeFimDoContrato(dataDoFimDoAluguel);
            alugarImovelBean.setCorretor(campoSelecioneCorretorDoAluguel.getSelectedItem().toString());
            alugarImovelBean.setImovel(campoSelecioneImovelDoAluguel.getSelectedItem().toString());
            alugarImovelBean.setCliente(campoSelecioneClienteDoAluguel.getSelectedItem().toString());
            alugarImovelBean.setValorNegociado(campoValorNegociadoDoAluguel.getText());
        
            facade.cadastrarAluguelDeImovel(alugarImovelBean);

            PainelDeDialogoCadastrarAlugarImovel dialogoCadastrarAlugarImovel = new PainelDeDialogoCadastrarAlugarImovel(null, true);
            PainelDeDialogoCadastrarAlugarImovel.textoCadastroDialogoAlugarImovel.setText("Cadastro realizado!");
            dialogoCadastrarAlugarImovel.setLocationRelativeTo(null);
            dialogoCadastrarAlugarImovel.setVisible(true);
            
            facade.alterarStatusDoImovel(Integer.parseInt(campoSelecioneImovelDoAluguel.getSelectedItem().toString()));

            campoSelecioneImovelDoAluguel.removeItem(campoSelecioneImovelDoAluguel.getSelectedItem().toString());

            limparCamposAlugarImovel();

            TelaPrincipalDoSistema.exibirPainelPesquisarAlugarImovel();
            PainelPesquisarAlugarImovel.mostrarTabelaAlugarImovel();

            TelaPrincipalDoSistema.botaoEditarAlugarImovel.setVisible(true);
            TelaPrincipalDoSistema.botaoExcluirAlugarImovel.setVisible(true);
            */
        }
        else{
            PainelDeDialogoAlugarImovel dialogoAlugarImovel = new PainelDeDialogoAlugarImovel(null, true);
            PainelDeDialogoAlugarImovel.textoNomeDialogoAlugarImovel.setText("Campo(s) inválido(s)!");
            dialogoAlugarImovel.setLocationRelativeTo(null);
            dialogoAlugarImovel.setVisible(true); 
        }
        
    }//GEN-LAST:event_botaoVenderImovelActionPerformed

   
    private void botaoLimparCamposDaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparCamposDaVendaActionPerformed
        limparCamposAlugarImovel();
    }//GEN-LAST:event_botaoLimparCamposDaVendaActionPerformed

 
    private void campoSelecioneImovelDoAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSelecioneImovelDoAluguelActionPerformed

        if (campoSelecioneImovelDoAluguel.getSelectedIndex() == 0) {
            campoValorNegociadoDoAluguel.setText("R$ 0,00");
        } 
        else {
            Dados.ImovelEstaticoAlugar = campoSelecioneImovelDoAluguel.getSelectedItem().toString().trim();    
            facade.listarCodigoDosImoveisAlugar();
            for (ImovelBean imovelBean : Dados.listaDeImoveisAlugarImovel) {
                if (imovelBean.getCodigo().toString().equals(campoSelecioneImovelDoAluguel.getSelectedItem().toString().trim())) {
                    campoValorNegociadoDoAluguel.setText(imovelBean.getValorCobrado());
                }         
            }
        }
        
        campoSelecioneClienteDoAluguel.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_campoSelecioneImovelDoAluguelActionPerformed

    private void campoSelecioneImovelDoAluguelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoSelecioneImovelDoAluguelMouseEntered
        
    }//GEN-LAST:event_campoSelecioneImovelDoAluguelMouseEntered

    private void campoSelecioneCorretorDoAluguelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoSelecioneCorretorDoAluguelMouseEntered
        
    }//GEN-LAST:event_campoSelecioneCorretorDoAluguelMouseEntered

    private void campoSelecioneImovelDoAluguelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneImovelDoAluguelFocusGained
        campoSelecioneImovelDoAluguel.setBackground(new Color(255,153,153));
        
    }//GEN-LAST:event_campoSelecioneImovelDoAluguelFocusGained

    private void campoSelecioneImovelDoAluguelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneImovelDoAluguelFocusLost
        campoSelecioneImovelDoAluguel.setBackground(new Color(255, 255, 255));
        
    }//GEN-LAST:event_campoSelecioneImovelDoAluguelFocusLost

    private void campoSelecioneCorretorDoAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSelecioneCorretorDoAluguelActionPerformed
        
    }//GEN-LAST:event_campoSelecioneCorretorDoAluguelActionPerformed

    private void campoSelecioneClienteDoAluguelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneClienteDoAluguelFocusGained
        campoSelecioneClienteDoAluguel.setBackground(new Color(255,153,153));
    }//GEN-LAST:event_campoSelecioneClienteDoAluguelFocusGained

    private void campoSelecioneClienteDoAluguelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSelecioneClienteDoAluguelFocusLost
        campoSelecioneClienteDoAluguel.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_campoSelecioneClienteDoAluguelFocusLost

    private void campoSelecioneClienteDoAluguelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoSelecioneClienteDoAluguelMouseEntered
        
    }//GEN-LAST:event_campoSelecioneClienteDoAluguelMouseEntered

    private void campoSelecioneClienteDoAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSelecioneClienteDoAluguelActionPerformed

    }//GEN-LAST:event_campoSelecioneClienteDoAluguelActionPerformed

    private void campoSelecioneCorretorDoAluguelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoSelecioneCorretorDoAluguelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSelecioneCorretorDoAluguelMouseExited

    private void campoDiaDataDeInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDiaDataDeInicioFocusGained
        campoDiaDataDeInicio.setBorder(new LineBorder(new Color(255,153,153),2,true));
    }//GEN-LAST:event_campoDiaDataDeInicioFocusGained

    private void campoDiaDataDeInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDiaDataDeInicioFocusLost
        campoDiaDataDeInicio.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoDiaDataDeInicioFocusLost

    private void campoDiaDataDeInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDiaDataDeInicioKeyReleased
        if(campoDiaDataDeInicio.getText().length() == 2){
            campoMesDataDeInicio.requestFocus();
        }
    }//GEN-LAST:event_campoDiaDataDeInicioKeyReleased

    private void campoMesDataDeInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMesDataDeInicioFocusGained
        campoMesDataDeInicio.setBorder(new LineBorder(new Color(255,153,153),2,true));
    }//GEN-LAST:event_campoMesDataDeInicioFocusGained

    private void campoMesDataDeInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMesDataDeInicioFocusLost
        campoMesDataDeInicio.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoMesDataDeInicioFocusLost

    private void campoMesDataDeInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMesDataDeInicioKeyReleased
        if(campoMesDataDeInicio.getText().length() == 2){
            campoAnoDataDeInicio.requestFocus();
        }
    }//GEN-LAST:event_campoMesDataDeInicioKeyReleased

    private void campoAnoDataDeInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAnoDataDeInicioFocusGained
        campoAnoDataDeInicio.setBorder(new LineBorder(new Color(255,153,153),2,true));
    }//GEN-LAST:event_campoAnoDataDeInicioFocusGained

    private void campoAnoDataDeInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAnoDataDeInicioFocusLost
        campoAnoDataDeInicio.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoAnoDataDeInicioFocusLost

    private void campoAnoDataDeInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoDataDeInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoDataDeInicioActionPerformed

    private void campoAnoDataDeInicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAnoDataDeInicioKeyReleased
        if(campoAnoDataDeInicio.getText().length() == 4){
            campoDiaDataDoFim.requestFocus();
        }
    }//GEN-LAST:event_campoAnoDataDeInicioKeyReleased

    private void campoDiaDataDoFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDiaDataDoFimFocusGained
        campoDiaDataDoFim.setBorder(new LineBorder(new Color(255,153,153),2,true));
    }//GEN-LAST:event_campoDiaDataDoFimFocusGained

    private void campoDiaDataDoFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDiaDataDoFimFocusLost
        campoDiaDataDoFim.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoDiaDataDoFimFocusLost

    private void campoDiaDataDoFimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoDiaDataDoFimKeyReleased
        if(campoDiaDataDoFim.getText().length() == 2){
            campoMesDataDoFim.requestFocus();
        }
    }//GEN-LAST:event_campoDiaDataDoFimKeyReleased

    private void campoMesDataDoFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMesDataDoFimFocusGained
       
       campoMesDataDoFim.setBorder(new LineBorder(new Color(255,153,153),2,true));
    }//GEN-LAST:event_campoMesDataDoFimFocusGained

    private void campoMesDataDoFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMesDataDoFimFocusLost
        
        campoMesDataDoFim.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoMesDataDoFimFocusLost

    private void campoMesDataDoFimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMesDataDoFimKeyReleased
        if(campoMesDataDoFim.getText().length() == 2){
             campoAnoDataDoFim.requestFocus();
         }
    }//GEN-LAST:event_campoMesDataDoFimKeyReleased

    private void campoAnoDataDoFimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAnoDataDoFimFocusGained
        
        campoAnoDataDoFim.setBorder(new LineBorder(new Color(255,153,153),2,true));
    }//GEN-LAST:event_campoAnoDataDoFimFocusGained

    private void campoAnoDataDoFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAnoDataDoFimFocusLost
        
        campoAnoDataDoFim.setBorder(new LineBorder(new Color(204,204,204),1,true));
    }//GEN-LAST:event_campoAnoDataDoFimFocusLost

    private void campoAnoDataDoFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoDataDoFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoDataDoFimActionPerformed

    private void campoAnoDataDoFimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoAnoDataDoFimKeyReleased
        if(campoAnoDataDoFim.getText().length() == 4){
            campoSelecioneCorretorDoAluguel.requestFocus();
        }
    }//GEN-LAST:event_campoAnoDataDoFimKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup botaoGrupoContrato;
    public static javax.swing.ButtonGroup botaoGrupoPeriodo;
    public static javax.swing.JButton botaoLimparCamposDaVenda;
    public static javax.swing.JButton botaoVenderImovel;
    public static javax.swing.JTextField campoAnoDataDeInicio;
    public static javax.swing.JTextField campoAnoDataDoFim;
    public static javax.swing.JTextField campoDiaDataDeInicio;
    public static javax.swing.JTextField campoDiaDataDoFim;
    public static javax.swing.JTextField campoMesDataDeInicio;
    public static javax.swing.JTextField campoMesDataDoFim;
    public static javax.swing.JComboBox<String> campoSelecioneClienteDoAluguel;
    public static javax.swing.JComboBox<String> campoSelecioneCorretorDoAluguel;
    public static javax.swing.JComboBox<String> campoSelecioneImovelDoAluguel;
    public static javax.swing.JTextField campoValorNegociadoDoAluguel;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JLabel txtDataEntega;
    public static javax.swing.JLabel txtDataEntega1;
    public static javax.swing.JLabel txtDataEntega2;
    public static javax.swing.JLabel txtDataEntega3;
    public static javax.swing.JLabel txtDataEntega4;
    public static javax.swing.JLabel txtDataEntega5;
    // End of variables declaration//GEN-END:variables

    private void limparCamposAlugarImovel() {
        campoDiaDataDeInicio.setText(null);
        campoMesDataDeInicio.setText(null);
        campoAnoDataDeInicio.setText(null);
        campoDiaDataDoFim.setText(null);
        campoMesDataDoFim.setText(null);
        campoAnoDataDoFim.setText(null);
        campoSelecioneCorretorDoAluguel.setSelectedIndex(0);
        campoSelecioneImovelDoAluguel.setSelectedIndex(0);
        campoSelecioneClienteDoAluguel.setSelectedIndex(0);
        campoValorNegociadoDoAluguel.setText("R$ 0,00");  
    }

    @Override
    public void execute() {
        String dataDeInicioDoAluguel = campoDiaDataDeInicio.getText() + "/" + campoMesDataDeInicio.getText() + "/" + campoAnoDataDeInicio.getText();
        String dataDoFimDoAluguel = campoDiaDataDoFim.getText() + "/" + campoMesDataDoFim.getText() + "/" + campoAnoDataDoFim.getText();

        alugarImovelBean = new AlugarImovelBean();
        alugarImovelBean.setDataDeInicioDoContrato(dataDeInicioDoAluguel);
        alugarImovelBean.setDataDeFimDoContrato(dataDoFimDoAluguel);
        alugarImovelBean.setCorretor(campoSelecioneCorretorDoAluguel.getSelectedItem().toString());
        alugarImovelBean.setImovel(campoSelecioneImovelDoAluguel.getSelectedItem().toString());
        alugarImovelBean.setCliente(campoSelecioneClienteDoAluguel.getSelectedItem().toString());
        alugarImovelBean.setValorNegociado(campoValorNegociadoDoAluguel.getText());

        facade.cadastrarAluguelDeImovel(alugarImovelBean);

        PainelDeDialogoCadastrarAlugarImovel dialogoCadastrarAlugarImovel = new PainelDeDialogoCadastrarAlugarImovel(null, true);
        PainelDeDialogoCadastrarAlugarImovel.textoCadastroDialogoAlugarImovel.setText("Cadastro realizado!");
        dialogoCadastrarAlugarImovel.setLocationRelativeTo(null);
        dialogoCadastrarAlugarImovel.setVisible(true);

        facade.alterarStatusDoImovel(Integer.parseInt(campoSelecioneImovelDoAluguel.getSelectedItem().toString()));

        campoSelecioneImovelDoAluguel.removeItem(campoSelecioneImovelDoAluguel.getSelectedItem().toString());

        limparCamposAlugarImovel();

        TelaPrincipalDoSistema.exibirPainelPesquisarAlugarImovel();
        PainelPesquisarAlugarImovel.mostrarTabelaAlugarImovel();

        TelaPrincipalDoSistema.botaoEditarAlugarImovel.setVisible(true);
        TelaPrincipalDoSistema.botaoExcluirAlugarImovel.setVisible(true);
        
    }


}
